### ISSUE TITLE
V1.0.5 bootstrap deployment

### ISSUE THREAD

**Issue by LeeSmet** [threefoldfoundation/tfchain#100]
## TODO:

- Create `v1.0.5` release
- Upload binaries
- Update bootstrap-1, 2, 3, and 5

## Blockers:

- Caddy certs are persistent right now, see: https://github.com/threefoldtoken/0-templates/issues/27

**Comment by LeeSmet** [comment]
Upgrade of the public explorers is currently blocked by:

**Comment by GlenDC** [comment]
This issue is finished, right?
