### ISSUE TITLE
Add graph line of average block creation time

### ISSUE THREAD

**Issue by LeeSmet** [threefoldfoundation/tfchain#103]
Some 50 blocks average, for now only calculate this in javascript

**Comment by LeeSmet** [comment]
Lets say the average is a sliding window, with a size of about 10% in relation to the amount of data points.

**Comment by LeeSmet** [comment]
deployed on testnet: https://explorer2.testnet.threefoldtoken.com/graphs.html

**Comment by GlenDC** [comment]
> The window is set to be 10% of the amount of data points. For the first windowsize datapoints, no average is displayed since it is not fully known yet

What if you in really get 110% of the amount of blocks the user requests. That would allow you to compute all data points, no?

**Comment by GlenDC** [comment]
For now it is fine as it is.

Closed by 5cfbfe2.
