### ISSUE TITLE
recovering a wallet might not load all possible addresses

### ISSUE THREAD

**Issue by GlenDC** [threefoldfoundation/tfchain#107]
When recovering a wallet, not all possible addresses (derived from that single seed) might be preloaded at that point, meaning the `tfchainc wallet` command might show a wrong balance. When creating a wallet using an existing seed (possible so using the `tfchainc wallet recover` command), it comes preloaded with 2500 keys. However, even though otherwise documented inside the codebase, more than 2500 keys can be loaded per seed. Such new addresses are created in two common instances:

+ each time a refund is made as part of a transaction, it is done so using a new address;
+ each time you call `tfchainc wallet address`, a new address is generated as well (but not used, so this is less of an issue);

It's the first instance that gives the poor UX. As refunds will go to addresses outside the range of 2500 addresses, and thus another recovery in the future, won't know that it has balances on some unknown addresses.

> If you know how many addresses your previous wallet had, you can keep calling `tfchainc wallet address`, until it has the same amount of addresses, at which point the shown balance should be correct.

**Comment by GlenDC** [comment]
First of all: it would probably be wise to limit the amount of addresses indeed. The intention seem to have been 2500, but there was apparently no code in place to prevent more from being created.

Secondly: it seems a bit over the top to create a new address for a refund. Why not simply use an owned wallet address, taken from (one of) the input(s)?

**Comment by GlenDC** [comment]
This might be fixed by a future Rivine update, if https://github.com/rivine/rivine/issues/309 gets resolved, but this is not all too sure, has to be investigated in more detail.

**Comment by robvanmieghem** [comment]
In the new Sia wallet code, no rescans are performed during unlock. Rescan should be done on seed loading or recover. A naive idea might be to create a much bigger hashmap with addresses during rescan.

**Comment by GlenDC** [comment]
solved by https://github.com/rivine/rivine/pull/424
