### ISSUE TITLE
create an automated way to receive tokens on testnet

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfchain#12]

**Comment by lafont-e** [comment]
Rob, could it be another api call (only available on debug and dev branches) that let any address ask for a fixed amount  (ie 100 coins)  tfchainc will announce the atm service and the server will create a block to  provide such amount to the address requesting it

**Comment by GlenDC** [comment]
Let's just do it as a simple html web-page. For now doesn't even need to be styled at all, and it can just a be a form.

The form will require an address, and a fixed amount of tokens will be send to it. There will be a time limit on how many tokens can be requested.

The Golang backend will render this form (as a simple http Server), and have a very simple backend to actually send coins using the REST API of a local tfchain daemon. We can use a embedded badgerdb for caching addresses that have received a token recently.
