### ISSUE TITLE
Rewrite explorer UI

### ISSUE THREAD

**Issue by LeeSmet** [threefoldfoundation/tfchain#120]
Since the state of the code (mainly the js) is pretty poor, it would be better to rewrite the whole thing from scratch, taking advantage of modern web coding advances (such as typescript, possibly a framework).

**Comment by DylanVerstraete** [comment]
Work in progress can be followed here: [https://github.com/threefoldtech/rivine-chain-explorer](https://github.com/threefoldtech/rivine-chain-explorer)
