### ISSUE TITLE
testnet token request for 019efdd5e04fbab9c4ad6c94e677f0957814a7b4d02b494337f9bc249ad20b35c8a853a97561d2

### ISSUE THREAD

**Issue by ahmedelsayed-93** [threefoldfoundation/tfchain#124]

**Comment by LeeSmet** [comment]
500 TTFT sent

https://explorer.testnet.threefoldtoken.com/hash.html?hash=6d26aa72d605affa14902d56fc1bd8a1ea466e36acd7064fb0ffddf077759783
