### ISSUE TITLE
Bootstrap nodes 2 and 3 down

### ISSUE THREAD

**Issue by LeeSmet** [threefoldfoundation/tfchain#129]
Both bootstrap nodes can no longer be reached, and from the network behavior (explorer graphs) it can be seen that they no longer create blocks. Most likely the entire nodes crashed. The nodes had an uptime of roughly 110 days, which also reflects the zero os version running on them (ledis, ORK, no zero robot, ...)

**Comment by LeeSmet** [comment]
Nodes have been restored (meaning they also run the current latest zero os build). block creators for testnet and explorers for main net have been brought up again (using macVlan setup). Block creators are not making any blocks yet due to https://github.com/threefoldtoken/0-templates/issues/38

**Comment by GlenDC** [comment]
Any progress on this @LeeSmet?
