### ISSUE TITLE
tfchainc atomicswap "--encoding json" Flag not working after v1.0.6 update

### ISSUE THREAD

**Issue by konceptzer0** [threefoldfoundation/tfchain#130]
Was working in this commit version:
https://github.com/JimberSoftware/rivine/commit/e465c93bde431d13d632f3128f3633d34dd96042

After updating to v1.0.6 the flag no longer does anything.

**Comment by GlenDC** [comment]
Just on a side note, you should really stop using your fork as you do. It would be much easier if you would just work within the `rivine/rivine` repo on your local $GOPATH, and add your jimberSoftware fork as a new remote. This way you could stay perfectly in sync with the rivine repo.

**Comment by GlenDC** [comment]
This issue is invalid. I just tried a local version of latest rivine master (commit xxx at the time of writing) and it seems to work just as intended.

Here some logs:

```
$ rivinec atomicswap auditcontract a51ff6b2af2dfae0cb56069d1cb8362768d598854c763f83726cc0bc88f279c4 ; echo $?
Atomic Swap Contract (condition) found:

Contract value: 100

Receiver's address: 014e35109941f7821616b054c0923e4796533ee3a848f93e90d15799a2b1b046f6950fda4628df
Sender's (contract creator) address: 01f68299b26a89efdb4351a61c3a062321d23edbc1399c8499947c1313375609adbbcd3977363c
Secret Hash: e9df20706bfbfefd1743832969733ad5dff081df30693088b375fc9199d8b4b6
TimeLock: 1528880080 (2018-06-13 10:54:40 +0200 CEST)
TimeLock reached in: 47h59m21.619031397s

found Atomic Swap Contract is valid
0
$ rivinec atomicswap auditcontract a51ff6b2af2dfae0cb56069d1cb8362768d598854c763f83726cc0bc88f279c4 --amount 100; echo $?
Atomic Swap Contract (condition) found:

Contract value: 100

Receiver's address: 014e35109941f7821616b054c0923e4796533ee3a848f93e90d15799a2b1b046f6950fda4628df
Sender's (contract creator) address: 01f68299b26a89efdb4351a61c3a062321d23edbc1399c8499947c1313375609adbbcd3977363c
Secret Hash: e9df20706bfbfefd1743832969733ad5dff081df30693088b375fc9199d8b4b6
TimeLock: 1528880080 (2018-06-13 10:54:40 +0200 CEST)
TimeLock reached in: 47h59m15.126207485s

found Atomic Swap Contract is valid
0
$ rivinec atomicswap auditcontract a51ff6b2af2dfae0cb56069d1cb8362768d598854c763f83726cc0bc88f279c4 --amount 10; echo $?
Atomic Swap Contract (condition) found:

Contract value: 100

Receiver's address: 014e35109941f7821616b054c0923e4796533ee3a848f93e90d15799a2b1b046f6950fda4628df
Sender's (contract creator) address: 01f68299b26a89efdb4351a61c3a062321d23edbc1399c8499947c1313375609adbbcd3977363c
Secret Hash: e9df20706bfbfefd1743832969733ad5dff081df30693088b375fc9199d8b4b6
TimeLock: 1528880080 (2018-06-13 10:54:40 +0200 CEST)
TimeLock reached in: 47h59m11.64109907s

unspent out's value 100  does not match the expected value 10
found Atomic Swap Contract does not meet the given expectations
1
```

As you can see, when using the amount flag, it does indeed check it, and it will return an error (status code 1) if it doesn't match the found contract's amount.

**Comment by GlenDC** [comment]
Please fork properly, without having to forcefully be out-of-sync with Rivine at all times due to your current approach of renaming the paths all times. So I recommend the following:

```
git clone git@github.com:rivine/rivine.git
cd $GOPATH/src/github.com/rivine/rivine
git remote add jimber git@github.com:JimberSoftware/rivine.git
```

Also please only report issues in this issue when using the tfchain codebase or a fork of it. You are using a fork of Rivine, and playing with that command, reading from your issue description, thus this issue should really be part of that repo. However this issue seems invalid, so this issue should really be part of no repo at the moment.

**Comment by jdelrue** [comment]
@GlenDC the issue is about the --encoding json flag which is broken. When not using the always yes function, but using json output, there is human readable output. We will fork properly without changing the paths.

We tested following configurations before doing a pull request:
- Encoding json & no yes flag -- broken
- Encoding human & no yes flag -- ok
- Encoding json & yes flag -- ok
- Encoding human & yes flag -- ok

**Comment by GlenDC** [comment]
You're right @konceptzer0 did indeed not mention the "amounts" flag. Not sure why I read that.

Can you please be more specific about broken...

As far as I know it is working. The `--encoding` and `-y/--yes` flags have nothing to do with each other. `--encoding` simply defines what the output format of the `STDOUT` should be, while the `-y/--yes` flag allows you to auto-respond `yes` to all questions.

So again. What you mean with broken...

**Comment by GlenDC** [comment]
> When not using the always yes function, but using json output, there is human readable output.

Yes but this output is in the STDERR though, not the STDOUT. But as you're in an automated environment, why would you not use the `-y` flag???

**Comment by jdelrue** [comment]
The point is that you specify --encoding json without the -y flag and you don't get JSON output but human output. It's confusing and feels wrong. Our dev lost time testing and thinking that json encoding was fully broken.

**Comment by GlenDC** [comment]
Again, it is not output, it is STDERR, which is still fine to have in automated environment for logging purposes. The encoding of STDOUT is unrelated to whether or not you wanting to have it encoded in a certain way. There are scenarios where you might want the output to be in JSON, but still want to be able to review and thus manually say yes.

Did your dev read the `--help` of the methods to be integrated? as that help is pretty clear:

```
      --encoding EncodingType   enum flag to define how to encode the output, options: json|human (default human)
  -y, --yes                     answer 'yes' to all yes/no questions without asking explicitly
```

Nowhere is written there that `--encoding json` is also applying `-y` for some reason... So not sure what you want me to do here?

**Comment by konceptzer0** [comment]
I was manually testing the flag from the terminal. I expected to be able to look at a JSON structure without publishing a transaction (hence not using the -y flag intentionally).

If I understand correctly, what gets printed in the terminal in this case comes from STDERR, not STDOUT. This is something I was not aware of.

**Comment by GlenDC** [comment]
All non-output data (human-readable review outputs, errors, ..) get printed to STDERR. Only the final output gets printed to STDOUT, if that exists. Meaning that if you have `--encoding json` you should only ever receive one final JSON object in the STDOUT, if that command actually has output and if it succeeded.

**Comment by konceptzer0** [comment]
Okay, thanks for the explanation. I understand it now and agree with how it is currently implemented.

I believe the confusion stemmed from the word "**output**" being used to refer to both the "**output** of a successful command" and the "human-readable review **output**". This made me think they are the same and I wasn't aware that a distinction was being made.
