### ISSUE TITLE
testnet block creators not syncing

### ISSUE THREAD

**Issue by LeeSmet** [threefoldfoundation/tfchain#134]
The block creators don't seem to be accepting new blocks building from the current master

**Comment by LeeSmet** [comment]
On my local deamon its refusing to sync on block 48287:

https://explorer.testnet.threefoldtoken.com/block.html?height=48287

Apparently the daemon seems to think that the blockstake is not respent

**Comment by GlenDC** [comment]
I guess my local daemon is stuck with syncing for same reason at https://explorer.testnet.threefoldtoken.com/block.html?height=45803

**Comment by GlenDC** [comment]
@LeeSmet `v1.0.6` ran fine, no? As the only peer I have connected is a `v1.0.6-alpha` one.

**Comment by LeeSmet** [comment]
yes v1.0.6 ran fine. I'm guessing something changed in the way the output ID's are calculated

**Comment by GlenDC** [comment]
There are unit tests for that though, unit tests which haven't changed since we introduced `1.0.4` or so. Will add the cases of those blocks to see if that is it. But it would surprise me.

**Comment by GlenDC** [comment]
I should eat my hat. Added a unit test, and indeed there seems to be an issue with block stake output IDs. Will investigate now.

**Comment by GlenDC** [comment]
Seems that both the computation of CoinOutputID and BlockStakeOutputID is wrong in the current tip code.

**Comment by GlenDC** [comment]
Found the error. Forgot to include version by default in the ID computation. Now the default is again using MarshalSia:

solution:

```diff
diff --git a/types/transactions.go b/types/transactions.go
index 1886061..4b67b32 100644
--- a/types/transactions.go
+++ b/types/transactions.go
@@ -201,22 +201,22 @@ func (t Transaction) encodeTransactionDataAsIDInput(w io.Writer) error {
 	if !exists {
 		return ErrUnknownTransactionType
 	}
-	td := TransactionData{
-		CoinInputs:        t.CoinInputs,
-		CoinOutputs:       t.CoinOutputs,
-		BlockStakeInputs:  t.BlockStakeInputs,
-		BlockStakeOutputs: t.BlockStakeOutputs,
-		MinerFees:         t.MinerFees,
-		ArbitraryData:     t.ArbitraryData,
-		Extension:         t.Extension,
-	}
 	if transactionIDEncoder, ok := controller.(TransactionIDEncoder); ok {
+		td := TransactionData{
+			CoinInputs:        t.CoinInputs,
+			CoinOutputs:       t.CoinOutputs,
+			BlockStakeInputs:  t.BlockStakeInputs,
+			BlockStakeOutputs: t.BlockStakeOutputs,
+			MinerFees:         t.MinerFees,
+			ArbitraryData:     t.ArbitraryData,
+			Extension:         t.Extension,
+		}
 		// use binary encoded specialized for ID Input
 		return transactionIDEncoder.EncodeTransactionIDInput(w, td)
 	}
 	// use the default binary encoding, if the controller does not require specialized
 	// encoding logic for ID purposes
-	return controller.EncodeTransactionData(w, td)
+	return t.MarshalSia(w)
 }
 
 // CoinOutputSum returns the sum of all the coin outputs in the
```
