### ISSUE TITLE
"Has been Spent" property in explorer web-UI can be incorrect 

### ISSUE THREAD

**Issue by GlenDC** [threefoldfoundation/tfchain#139]
When using one of our official public web explorers (<http://explorer.threefoldtoken.com>), you can check for a wallet addresses which (coin) outputs relate to it. Per output it also shows whether or not the output has already been spent. This property used to work, or at least I never noticed it producing lies in the past. When looking at it last night however I noticed that for the last couple of transactions it was apparently unaware that the outputs that had been spent, had been spent.

## Example

You can see an output being used as an input of a transaction:

<img width="800" alt="screen shot 2018-06-18 at 08 07 11" src="https://user-images.githubusercontent.com/3900482/41520589-b3020344-72ce-11e8-9045-1c4e5e7d4bbe.png">

> source: https://explorer.threefoldtoken.com/hash.html?hash=011fe33d06d3315102fc4b692664fa2d96c31b37d60d479894d59047b49d6acf8321abfdfe3169

The output, when seen in the wallet that used to own it, is still shown as "not spent" however:

<img width="1057" alt="screen shot 2018-06-18 at 08 04 19" src="https://user-images.githubusercontent.com/3900482/41520592-b7f19fe0-72ce-11e8-827e-0b115ea14a62.png">

> source: https://explorer.threefoldtoken.com/hash.html?hash=a8160620f4982065fb1bbd385716edf6d0bbd2b2fcfc8634c1c80d879d270a54

**Comment by GlenDC** [comment]
Seems like an issue bug than. Feel free to resolve it in case you have some minutes to kill while waiting for a debugging process.

**Comment by LeeSmet** [comment]
https://github.com/rivine/rivine/issues/407

**Comment by GlenDC** [comment]
closed via rivine-vendor-dep update: 7dc0288f636bbf767f1c0094c3a9d4f292edfdf4
