### ISSUE TITLE
display (Git) commit ID in footer of explorer web-UI

### ISSUE THREAD

**Issue by GlenDC** [threefoldfoundation/tfchain#140]
This would make it very easy to see for any web-explorer to know at which commit of our repository it is running. Ideally this is done as part of the `explorer` Makefile target.

**Comment by LeeSmet** [comment]
Maxime will take a look

**Comment by LeeSmet** [comment]
Will see if the release of the explorer can be changed: right now we always make a tar file of the frontend directory inside the repo. Dropping in this variable would then always mean a file change as part of the explorer release. A better approach would be:

- create temp dir
- copy the frontend dir to this temp dir
- replace variables with w/e we want
- make tar from this temp directory.

This would mean there is no change when the explorer is released in the git directory but the required info is added to the official release. Also this would make it easier imo to find out where the variables need to be inserted.
