### ISSUE TITLE
Prevent caching for explorer pages

### ISSUE THREAD

**Issue by LeeSmet** [threefoldfoundation/tfchain#149]

**Comment by GlenDC** [comment]
Maxime could do this one as well, when he finished his other issues.

**Comment by GlenDC** [comment]
Closed by 19ce9b8a593cf323716741305986875acad615a0, 097355cbca071f679fd09aa51c05a6c387e244ee, b78ab0ee85a1e2360b1d50220439997a7d70932f and 2faa9e3b7ac11e6ab33021ab048afb015714a276.
