### ISSUE TITLE
Testnet token request for several addresses (automatic swap staging env)

### ISSUE THREAD

**Issue by jdelrue** [threefoldfoundation/tfchain#151]
0170d7301d1c957fcbe40a780137151d73411ad054d9603ae0a7af190a3bb6636a06106f0c5c29

013cc589770bebd0f5aea91fea03f0f6a515af2f0b6588f83983bfc6db4d4f998d6f38e501fb88

01a644c8136bfc99137ef73508da5f768e52f5d3e6c5460110f947e767164e38661bd71c819f72

01b36dc08fb47dca6361ab8c4bb3d4156226d1c00a39db13434354e1b17c11262ee9ea822c0abc

01ba50f0c06b9f8134f13d027d3fe782a31fe47c38da495f9ea4e21a90437643b66f58858194d3

**Comment by LeeSmet** [comment]
150 TFT sent to each address

**Comment by LeeSmet** [comment]
https://explorer.testnet.threefoldtoken.com/hash.html?hash=1636e3ee7610ae3c706bef65c4bfb52a8ee4e35e9e6b390ccf562f45b1062043
