### ISSUE TITLE
inconsistent spendings between unlockhash- and outputid- explorer page 

### ISSUE THREAD

**Issue by GlenDC** [threefoldfoundation/tfchain#152]
When looking for the NilUnlockHash on testnet, there is one regular NilConditioned output which is marked as not spend yet. However, when trying to spend it using the `tfchainc` CLI the item is reported as not existing (meaning it it is no longer as unspent in the consensus). This is indeed confirmed by the web explorer by going to the actual hash page of the output (using the outputid of the output which the NilCondition conditions).

#### Example

unlock hash (NilUnlockHash):

![screen shot 2018-06-27 at 18 19 10](https://user-images.githubusercontent.com/3900482/41986608-ec19ec9a-7a36-11e8-9b5e-5746462248d6.png)

> original source: https://explorer.testnet.threefoldtoken.com/hash.html?hash=000000000000000000000000000000000000000000000000000000000000000000000000000000

outputID:

![screen shot 2018-06-27 at 18 19 21](https://user-images.githubusercontent.com/3900482/41986617-f2726680-7a36-11e8-9bb2-764d626be57d.png)

> original source: https://explorer.testnet.threefoldtoken.com/hash.html?hash=ee664902d9bc563e57f912b10a864b113747c1636057c973cdcca29c9719ff3d

**Comment by LeeSmet** [comment]
Fixed after explorer dbs resynced
