### ISSUE TITLE
Transaction does not get submitted to the network

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/tfchain#156]
Steps to reproduce:
1. Unlock the wallet.
2. Execute the following command.
3. Wait

**CONSOLE 1:**
Mykolas-MacBook-Pro:cmd nick$ ./tfchaind 
Loading...
(0/5) Loading daemon of tfchain...
(1/5) Loading gateway...
(2/5) Loading consensus...
(3/5) Loading transaction pool...
(4/5) Loading wallet...
(5/5) Loading block creator...
Finished loading in 0.242510281 seconds
Rescanning consensus set...
Scanned to height 65355...
Done!

**CONSOLE2:** 
Mykolas-MacBook-Pro:cmd nick$ ./tfchainc wallet send coins '{"type":1,"data":{"unlockhash":"0128d58068852344fc27243aa0c4adfc4550edf11b619d98740755ed18d925880f55051d3a188e"}}' 10
Succesfully sent coins as transaction 1484f9bad9c3b126effa0a88e1cd5c5671abcf7608cc680a22662c99f1ca4005
Sent 10 TFT to 0128d58068852344fc27243aa0c4adfc4550edf11b619d98740755ed18d925880f55051d3a188e (using ConditionType 1)
Mykolas-MacBook-Pro:cmd nick$ ./tfchainc wallet 
Wallet status:
Encrypted, Unlocked
Confirmed Balance:   **94.69835318 TFT
Locked Balance:      **42.25 TFT
Unconfirmed Delta:   - 10.1 TFT
BlockStakes:         0 BS
Mykolas-MacBook-Pro:cmd nick$ ./tfchainc 
Synced: Yes
Block:  d9a660a87875d599d642d90f9b19b8f413aff151bf6861788e6aeab77ff1df45
Height: 66012
Target: [0 8 54 237 188 179 67 194 209 51 227 139 225 45 53 250 98 252 144 163 169 238 12 10 234 58 52 207 28 149 196 47]
Mykolas-MacBook-Pro:cmd nick$ ./tfchainc 
Synced: Yes
Block:  0a4108bc2fbbc88ee3f2bc98190f80ab03b8c3678b56c4ebdc8ddb01f293e6cf
Height: 66021
Target: [0 8 54 237 188 179 67 194 209 51 227 139 225 45 53 250 98 252 144 163 169 238 12 10 234 58 52 207 28 149 196 47]
Mykolas-MacBook-Pro:cmd nick$ ./tfchainc wallet 
Wallet status:
Encrypted, Unlocked
Confirmed Balance:   **94.69835318 TFT
Locked Balance:      **42.25 TFT
Unconfirmed Delta:   - 10.1 TFT
BlockStakes:         0 BS
Mykolas-MacBook-Pro:cmd nick$

Mykolas-MacBook-Pro:cmd nick$ ./tfchainc version
Tfchain Client v1.0.7

Mykolas-MacBook-Pro:cmd nick$ ./tfchainc gateway list
8 active peers:
Version  Outbound  Address
1.0.7    Yes       81.242.206.228:23112
1.0.7    Yes       185.69.166.24:23112
1.0.7    Yes       207.154.221.32:23112
1.0.7    Yes       91.179.158.23:23112
1.0.7    Yes       185.69.166.28:23112
1.0.7    Yes       185.69.166.27:23112
1.0.7    Yes       185.69.166.23:23112
1.0.5    Yes       5.45.120.191:23112

Mykolas-MacBook-Pro:cmd nick$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.13.6 (17G65)
      Kernel Version: Darwin 17.7.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Mykola’s MacBook Pro
      User Name: Mykola Babenko (nick)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 6 days 10:17

**PLEASE NOTE**
Transaction sent with timelockhash is processed properly:

Mykolas-MacBook-Pro:cmd nick$ ./tfchainc wallet send coins '{"type":3,"data":{"locktime":1532377484,"condition":{"type":1,"data":{"unlockhash":"0128d58068852344fc27243aa0c4adfc4550edf11b619d98740755ed18d925880f55051d3a188e"}}}}' 10
Succesfully sent coins as transaction defc03474630cf5fd26718af3621aed6d9f214cb8fb2b996b0974e84c46584b1
Sent 10 TFT to 0128d58068852344fc27243aa0c4adfc4550edf11b619d98740755ed18d925880f55051d3a188e (using ConditionType 3)
Mykolas-MacBook-Pro:cmd nick$ ./tfchainc wallet
Wallet status:
Encrypted, Unlocked
Confirmed Balance:   **94.69835318 TFT
Locked Balance:      **42.25 TFT
Unconfirmed Delta:   - 10.1 TFT
BlockStakes:         0 BS
Mykolas-MacBook-Pro:cmd nick$ ./tfchainc 
Synced: Yes
Block:  a9fb2b3f75ec1f17b5f3e88d3313a1db3da7ff2d8f05986be6cdd7b8d27f6943
Height: 66062
Target: [0 8 54 237 188 179 67 194 209 51 227 139 225 45 53 250 98 252 144 163 169 238 12 10 234 58 52 207 28 149 196 47]
Mykolas-MacBook-Pro:cmd nick$ ./tfchainc 
Synced: Yes
Block:  0213edfe9aac86c109a80bb062804ed4b990ac5fb1aae5c1ccdae836546fb8ea
Height: 66069
Target: [0 8 54 237 188 179 67 194 209 51 227 139 225 45 53 250 98 252 144 163 169 238 12 10 234 58 52 207 28 149 196 47]
Mykolas-MacBook-Pro:cmd nick$ ./tfchainc wallet
Wallet status:
Encrypted, Unlocked
Confirmed Balance:   **84.59835318 TFT
Locked Balance:      **42.25 TFT
Unconfirmed Delta:   + 0 TFT
BlockStakes:         0 BS

**Comment by GlenDC** [comment]
@nbabenko could you try to reproduce it once again. If you notice a transaction being stuck in the pool again (while you are sure there are peers connected (make sure to post the list at that point again)) you should run the following command: `curl -A "Rivine-Agent" "localhost:23110/transactionpool/transactions"` and post me its output.

I was trying to reproduce your bug in all kinds of ways, and so far I cannot reproduce it. Trying to deduce, by reasoning about the code, about why you might suffer from this has so far not really gave me any useful result either.

**Comment by nbabenko** [comment]
hm, it works now.
