### ISSUE TITLE
Write a public feature description + motivation for the coin creation 

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfchain#171]
there is already a technical description of the transaction types: https://github.com/threefoldfoundation/tfchain/blob/master/doc/transactions.md#coin-creation-transactions

**Comment by zaibon** [comment]
@robvanmieghem link points to nothing

**Comment by GlenDC** [comment]
Edited description, the technical doc already lives on master by now at <https://github.com/threefoldfoundation/tfchain/blob/master/doc/transactions.md#coin-creation-transactions>.

Doc written for this issue (the non technical one) lives at:
