### ISSUE TITLE
testnet token request for 0168b79cef6c939389c12e2cacedbff84f2fbfd797c9a36f7dfaa0ef078a0612780dab39067708

### ISSUE THREAD

**Issue by dancingfrog** [threefoldfoundation/tfchain#172]

**Comment by LeeSmet** [comment]
900 tokens sent,

https://explorer.testnet.threefoldtoken.com/hash.html?hash=3e44c2697a7c37c378b39b0aebaf46798022c757543868ed97e00d9d2a7fed19
