### ISSUE TITLE
explorer.threefoldtoken.com unavailable

### ISSUE THREAD

**Issue by LeeSmet** [threefoldfoundation/tfchain#208]
On the 13th of november, explorer.threefoldtoken.com and explorer.testnet.threefoldtoken.com were unavailable. It seemed that the physical node both containers were running on froze.

This led to the following chain of events:

- Reboot of node. This meant that the zero-os version was updated to the latest master at the time (`v1.5.0-rc1`). 
- As a result of this update, the old flist format was incompatible, and the templates running on the node robot which should bring back the explorers had errors.
- Issue in the templates had been resolved by updating them, see https://github.com/threefoldtoken/0-templates
- The current production and edge flists were migrated from https://hub.gig.tech to https://hub.grid.tf
- The services were changed to pull from the new hub.

It seems that @zaibon had some issues when updating the services as there are now new secrets used by these services

Furthermore only one node is updated to the new format, the other ones will need to follow as well.

**Comment by GlenDC** [comment]
> Issue in the templates had been resolved by updating them,
> see https://github.com/threefoldtoken/0-templates

Please migrate these changes to <https://github.com/threefoldfoundation/tfchain-templates/tree/a3a25e91b1db2fb9d1e0d5355bcaf7b7405decec>, as that is the repo that is planned to be used once we took over the deployment and management of these nodes (see #182).

**Comment by LeeSmet** [comment]
For the merge, I tried cherry picking, however it seems there are a lot of merge conflicts. It seems that the development branch has not been merged into master. Not sure if we should do this first.

**Comment by GlenDC** [comment]
What merge are you talking about? and what dev/master branch? Neither <https://github.com/threefoldtoken/0-templates> or <https://github.com/threefoldfoundation/tfchain-templates> has a dev branch AFAIK. Please clarify as your comment confuses me @LeeSmet.

**Comment by LeeSmet** [comment]
my bad, it seems the templates live in multiple repo's, the templates in https://github.com/threefoldfoundation/tfchain-templates have the initial commits from https://github.com/threefoldtoken/0-templates. In a subsequent commit, further changes were added which happened in the https://github.com/threefoldtech/0-templates repo (I assume the existing templates from the prior repo were copied here). Since the new updates are now once again applied on the initial threefoldtoken template repo, there  are 2 diverging branches. Trying to cherry pick will lead to merge conflicts between them. So I am not sure what the best approach is. Try to merge them in, or ask someone who actually worked on them for help as to make sure nothing breaks
