### ISSUE TITLE
web explorer can't handle anything except v0/v1 transactions

### ISSUE THREAD

**Issue by LeeSmet** [threefoldfoundation/tfchain#212]
For instance, https://explorer2.testnet.threefoldtoken.com/hash.html?hash=01472c099db3d698d79c5f797093be9ea35dc7d2c3a18278896d32df64fd3ffe08c4e0f2d34f1d is an address which has a V144 txn. On the linked page, rendering of transactions currently fails because this transaction type does not have a `coinoutputs` attribute.

[This check](https://github.com/threefoldfoundation/tfchain/blob/master/frontend/explorer/public/js/hash.js#L1591) needs to be updated to allow more transaction types.

Its quite possible there are other pages with similar issues as well

**Comment by GlenDC** [comment]
Fairly sure I already solved most, if not all, of these issues on master. You might want to run a testnet explorer locally, using a remote testnet daemon, and validate all kinds of pages. If OK you could perhaps quickly deploy a new edge tfchain explorer (just the explorers, not the actual daemons I think).

Could you pick this up @leesmet?

**Comment by GlenDC** [comment]
Linked the issue to the November bugs-and-issues story threefoldtech/home#49 as well.

**Comment by LeeSmet** [comment]
Indeed, seems to work locally. I'll slide in some time for #210 as well on the issue list and redeploy once that is done

**Comment by LeeSmet** [comment]
Explorer front ends on testnet have been updated and now render correctly.

**Comment by GlenDC** [comment]
So why is this issue not closed? What is still to be done?

**Comment by LeeSmet** [comment]
I guess someone still needs to press the close issue button, seems I forgot about that last time :)

**Comment by GlenDC** [comment]
@LeeSmet found some more issues, fixed in 12cdb4b625ea7e48c25600f997f1df450266b8a1, pushed to master. You might want to redeploy again.
