### ISSUE TITLE
Design for the token webshop using bitcoin

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfchain#213]

**Comment by VonSub** [comment]
Can you guys provide me with just a bit more specs?
Now have Shapeshift as an example, but do we also need a login, registering, etc..?
Or just:

- Amount + TF address
- BTC QR
- Success / Failed Page

**Comment by robvanmieghem** [comment]
no registration or login required
btw, failure is not an option ;-)

**Comment by VonSub** [comment]
Do we need email addresses?
To contact people about their "order" and update them about the status of their "swap/shift/..."

**Comment by VonSub** [comment]
first prototype:

https://invis.io/NTPANRN3A49#/333333358_Desktop_HD_Copy

**Comment by GlenDC** [comment]
> Do we need email addresses?

I don't think so. That information is all available within the App.
AFAIK the website should be stateless and request no information from the user other than required to generate the correct code needed to make the desired transfer.

**Comment by GlenDC** [comment]
By the way, I think we can remove also the TFT address to send to. It would make it easier and faster for the user. As the user is scanning this QR code with their TF application I assume that the App can fill in the address for the user. Or am I missing something here @robvanmieghem?

**Comment by GlenDC** [comment]
> AFAIK the website should be stateless and request no information from the user other than required > to generate the correct code needed to make the desired transfer.

 I was wrong here. I completely misunderstood the concept.

> By the way, I think we can remove also the TFT address to send to. It would make it easier and faster > for the user. As the user is scanning this QR code with their TF application I assume that the App can > fill in the address for the user.

I was wrong here as well.

---

Now that I do understand the concept, all looks pretty good as it is. Not sure if it needs an email address though, perhaps we could just provide a unique URL they can use to track their order, than they can still choose to save the URL somewhere. Visiting that URL could be in a similar design as the webpages you get when tracking a package you're about to receive, showing the different steps, and where in the process the TFT order is.

> Which would mean, no to the stateless, as stateless is anyhow not a possibility now that I know the concept. It is in the end the shop that is sending the TFT tokens to the user's wallet.

**Comment by VonSub** [comment]
prototype is finished.
where to get this verified this is indeed what we want so we can start building a functional page?

TCs, PS and FAQ are up for debate...so 404-ed them for now.
