### ISSUE TITLE
explorer.threefoldtoken.com and explorer.testnet.threefoldtoken.com down

### ISSUE THREAD

**Issue by LeeSmet** [threefoldfoundation/tfchain#215]

**Comment by GlenDC** [comment]
@leesmet, please also track issues on the other technology repos, should there be an issue in other places of our stack. If so, please link those issues to here and follow them up, so we don't keep suffering from this. Because more and more use cases will rely on our public explorers.

**Comment by LeeSmet** [comment]
Tracking issue @ https://github.com/threefoldtech/0-core/issues/85

**Comment by LeeSmet** [comment]
Node is having the same issue. Unreachable through zerotier (also listed as down on the zerotier network page), so it cannot be rebooted remotely.

**Comment by LeeSmet** [comment]
Node has been rebooted and services are operational again

**Comment by GlenDC** [comment]
Do we already have a follow-up issue to find out why it stopped working? If not, please create. And link from here

**Comment by LeeSmet** [comment]
https://github.com/threefoldfoundation/tfchain/issues/220

**Comment by LeeSmet** [comment]
mainnet explorer dns is now served on the node hosting explorer2. Testnet dns has not been moved however.

**Comment by LeeSmet** [comment]
Update: In the meantime down again after the dns was moved back to the test node and it crashed.

**Comment by LeeSmet** [comment]
Closing once again, these domains run on fruit-jr for now. Will move them back to the zero-os based bootstrap node that is being set up to replace the broken one once that is fully prepped
