### ISSUE TITLE
support new transaction type to send tft to an ethereum address

### ISSUE THREAD

**Issue by GlenDC** [threefoldfoundation/tfchain#218]
Part of story <https://github.com/threefoldtech/home/issues/56>.

Will use Rivine encoding.

Required to unblock Mobicage team.

**Comment by GlenDC** [comment]
Proposed Tx:

```json
// EthereumAddresPaymentTransaction defines the Transaction (with version 0xD1)
// used to pay to an ethereum address, previously registered on tfchain,
// coupled to the given TFT address
EthereumAddresPaymentTransaction struct {
	// the registered TFT address, coupled to the ethereum address
	// to which the desired amount will be paid to.
	// This amount can be calculated using the following formula: sum(inputs)-sum(fees)-refundOutput
	Address types.UnlockHash

	// TransactionFee defines the regular Tx fee.
	TransactionFee types.Currency `json:"txfee"`

	// OracleFee defines the oracle fee.
	OracleFee types.Currency `json:"oraclefee"`

	// CoinInputs are only used for the required fees,
	// which contains the regular Tx fee as well as the additional fees,
	// to be paid for the address registration. At least one CoinInput is required.
	CoinInputs []types.CoinInput `json:"coininputs"`
	// RefundCoinOutput is an optional coin output that can be used
	// to refund coins paid as inputs for the required fees.
	RefundCoinOutput *types.CoinOutput `json:"refundcoinoutput,omitempty"`
}
````

**Comment by LeeSmet** [comment]
Are we going to register an ETH address first as well before we can send tft to it?

**Comment by GlenDC** [comment]
Yes, that’s a requirement afaik, my commented address in the proposed tx says so

**Comment by LeeSmet** [comment]
I thought we just wanted to be able to include *any* valid ETH address as a target, without the need for registering it first?

**Comment by GlenDC** [comment]
> I thought we just wanted to be able to include any valid ETH address as a target, without the need for registering it first?

dunno, it is possible as well, would mean the given address (in the tx) could just be a byte array of 20 bytes instead of the unlockhash currently used.

I suppose it does make sense that this can be useful and thus might have to be allowed. But than again, it is currently not possible to go from the ERC-20 fund to TFT via an address not of you, so not sure why in on direction that is allowed and not the other.

**Comment by LeeSmet** [comment]
The other direction is mandatory, whereas this one is not really required. And given the context of why we are implementing this, it feels like we should try to minimize the amount of steps required

**Comment by GlenDC** [comment]
This is now how such a Tx (JSON-encoded) looks like on the chain, as it is:

```json
{
	"version": 208,
	"data": {
		"address": "0123456789012345678901234567890123456789",
		"value": "200000000000",
		"txfee": "1000000000",
		"coininputs": [{
			"parentid": "9c61ec964105ec48bc95ffc0ac820ada600a2914a8dd4ef511ed7f218a3bf469",
			"fulfillment": {
				"type": 1,
				"data": {
					"publickey": "ed25519:7469d51063cdb690cc8025db7d28faadc71ff69f7c372779bf3a1e801a923e02",
					"signature": "a0c683e8728710b4d3cd7eed4e1bd38a4be8145a2cf91b875986870aa98c6265d76cbb637d78500010e3ab1b651e31ab26b05de79938d7d0aee01f8566d08b09"
				}
			}
		}],
		"refundcoinoutput": {
			"value": "99999476000000000",
			"condition": {
				"type": 1,
				"data": {
					"unlockhash": "011c17aaf2d54f63644f9ce91c06ff984182483d1b943e96b5e77cc36fdb887c846b60460bceb0"
				}
			}
		}
	}
}
```

The current implementation (including a new CLI command to make such a transfer) can be found at: https://github.com/threefoldfoundation/tfchain/commit/efc582fdf293afbd329752aa6d848aedd3e6d980

**Comment by GlenDC** [comment]
This Tx Type is now fully working. You can send such a conversion Tx using the CLI command `tfchainc wallet send erc20funds`.

Documentation has also been added (<https://github.com/threefoldfoundation/tfchain/blob/erc20-conversion-tx/doc/transactions.md#erc20-convert-transaction>)  and the web explorer has also support already:

<img width="533" alt="screen shot 2018-12-07 at 22 45 24" src="https://user-images.githubusercontent.com/3900482/49674464-6acf8200-fa72-11e8-97a8-29930b5333fb.png">

Only thing that is left to do is define the flow of the bridge, and how it consume this Tx (just once), resulting in an ERC20 contract update.
