### ISSUE TITLE
Research how to set up an ERC20 proxy contract

### ISSUE THREAD

**Issue by LeeSmet** [threefoldfoundation/tfchain#221]
A "simple" proxy which just proxies calls to an address might not work, since this only loads the code from the target contract and executes it in its own environment. Thus the storage must remain the same in all contracts. It might however be possible to move the storage to its own contract, which would mean we don't have to worry about this when a new token contract is written

**Comment by LeeSmet** [comment]
Some interesting resources: https://blog.zeppelinos.org/smart-contract-upgradeability-using-eternal-storage/. This seems to be mostly what we would need for the final contract

**Comment by robvanmieghem** [comment]
It's still a mess but you are absolutely right, in order to keep the state, we need to move it to immutable contracts. Let's make sure we seperate it correctly( tokenstorage, withdrawal addresses,...)
