### ISSUE TITLE
Basic erc20 contract and proxy contract

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfchain#223]
Based upon findings in https://github.com/threefoldfoundation/tfchain/issues/221 for upgradeability
Please include a diagram ( preferrably in svg , using Inkscape for example) and a markdown doc to explain the different contracts.

**Comment by LeeSmet** [comment]
Basic contract and proxy setup contracts are done, still need to:
- Define ownership (create "owned" contract, figure out how to make that work with multiple owners)
- Define additional capabilities for the contracts given that we want to be able to mint and burn coins, etc
