### ISSUE TITLE
erc20 validator module

### ISSUE THREAD

**Issue by LeeSmet** [threefoldfoundation/tfchain#224]
Although we initially said that we would create separate module for the erc20 validator (IIRC), I see some issues with this approach. Mainly, once the block is accepted in the consensus set, there is no way to remove it again (except a reorg). Furthermore, if we do this validation in a new module which receives updates form the consensus module, and use this new module in our blockcreator to verify if the current active fork indeed does not contain faulty transactions, the best we can do is halt these block creators. So the only time we can verify the erc20 txns before the block is accepted in the cs, is in the consensus module itself. This means that the cs module as exposed by rivine would need to accept custom rules. If not, we can't stop fautly/malicious block creators from inserting faulty/fake erc20 to tft txns.

**Comment by GlenDC** [comment]
I think we already discussed this. One of the suggested approaches back than was to have it be a easy to easy library (go package), such that we can optionally plug it into the validation of this transaction type (via its controller). Than anyone who wishes can enable this (requiring an ETH node running somewhere, or perhaps we can do it directly from that Library using go-eth). Probably all our block creators should enable that, as those are the ones creating the blocks anyhow.

It's nasty though, but I think that is what was discussed last time I brought this topic up.

**Comment by LeeSmet** [comment]
I see, somehow I thought we didn't really reach that decision in the meeting. Seems I somehow forgot that part then

**Comment by GlenDC** [comment]
Will start on creating a first super-basic version of this tomorrow, so we can already have something to play with, and be able to start (further discussions/follow-ups) from there.

**Comment by GlenDC** [comment]
* [ ] In a first phase we'll already be happy if we can validate a transaction using its TransactionID. What will be validated:
  * [ ] That the transactionID points to a valid transaction (exists, is the expected operation on the expected contract);
  * [ ] That the content of the transaction is as expected (right amount, to right withdrawal address);
  * [ ] That transaction has a parent block with a height equal to or less than the current height minus 6 (min block delay of 6 blocks);
* [ ] once that works, we'll clean it up a bit and merge it into our client;

**Comment by GlenDC** [comment]
Did a quick prototype using the `etherscanapi`.

> Note that I did have to hack some stuff in the lib, see <https://github.com/nanmu42/etherscan-api/issues/5#issuecomment-449409004> for more context.

In the prototype I ensured to validate all checks from first phase as listed in previous comment (
https://github.com/threefoldfoundation/tfchain/issues/224#issuecomment-449351639).

Here is the prototype code:

```go
package main

import (
	"encoding/hex"
	"fmt"
	"log"
	"math/big"
	"os"
	"strings"

	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/common"
	"github.com/nanmu42/etherscan-api"
	"github.com/threefoldfoundation/tfchain/pkg/config"
	"github.com/threefoldfoundation/tfchain/pkg/eth/erc20/contract"
	tftypes "github.com/threefoldfoundation/tfchain/pkg/types"
	rclient "github.com/threefoldtech/rivine/pkg/client"
	"github.com/threefoldtech/rivine/types"
)

func main() {
	if len(os.Args) != 5 {
		log.Fatal("expected 4 positional argument: <apiKey> <txHash> <targetUnlockHash> <expectedValueInTFT>")
	}
	apiKey := os.Args[1]
	txHash := os.Args[2]

	// generate the expected ERC20 Address, so we can validate
	var targetUnlockHash types.UnlockHash
	err := targetUnlockHash.LoadString(os.Args[3])
	if err != nil {
		log.Fatalf("error while decoding target unlock hash: %v", err)
	}
	expectedERC20Address := tftypes.ERC20AddressFromUnlockHash(targetUnlockHash)
	fmt.Printf("Expected ERC20 Withdrawal address: %v\n", expectedERC20Address)

	// decode the expected TFT
	cc := rclient.NewCurrencyConvertor(
		config.GetCurrencyUnits(),
		config.GetBlockchainInfo().CoinUnit,
	)
	expectedTFTValue, err := cc.ParseCoinString(os.Args[4])
	if err != nil {
		log.Fatalf("error while decoding expected transfer value: %v", err)
	}
	fmt.Printf("Expected ERC20 transfer value: %v\n", cc.ToCoinStringWithUnit(expectedTFTValue))

	fmt.Println()

	// create a API client for specified ethereum net
	// there are many pre-defined network in package
	client := etherscan.New(etherscan.Rinkby, apiKey)

	// Get Transaction Object
	tx, err := client.ProxyGetTransactionByHash(txHash)
	if err != nil {
		// NOTE: if Tx Doesn't exist, this will error, so that is the first VALIDATION-CHECK
		log.Fatalf("error while fetching tx object for hash %v: %v", txHash, err)
	}
	fmt.Println("CHECK PASSED: Tx Exists and can be decoded!")

	// ABI-Decode the Tx Input, using the Generated Contract Go Code
	parsedABI, err := abi.JSON(strings.NewReader(contract.TTFT20ABI))
	if err != nil {
		log.Fatalf("error while parsing contract ABI: %v", err)
	}

	decodeData, err := hex.DecodeString(tx.Input[2:])
	if err != nil {
		log.Fatalf("error while decoding Tx %v input: %v", txHash, err)
	}
	if len(decodeData) <= 4 {
		log.Fatalf("unexpected decode data length: %v", len(decodeData))
	}

	// first 4 bytes contain the id, so let's get method using that ID
	method, err := parsedABI.MethodById(decodeData[:4])
	if err != nil {
		log.Fatalf("failed to get method using its parsed id: %v", err)
	}
	if method.Name != "transfer" {
		log.Fatalf("unexpected name for unpacked method ID: %s", method.Name)
	}

	params := struct {
		To     common.Address
		Tokens *big.Int
	}{}
	err = method.Inputs.Unpack(&params, decodeData[4:])
	if err != nil {
		log.Fatalf("error while unpacking transfer Tx %v input: %v", txHash, err)
	}
	fmt.Println("CHECK PASSED: Input is correct and Tx is using the transfer method")

	toAddress := params.To.String()
	expectedToAddress := common.Address(expectedERC20Address).String()
	if toAddress != expectedToAddress {
		log.Fatalf("unexpected to address %v: expected address %v", toAddress, expectedToAddress)
	}
	fmt.Println("CHECK PASSED: ToAddress equals the expected withdrawal address")

	erc20Tokens := big.NewInt(0).Div(params.Tokens, erc20Precision)
	tfTokens := types.NewCurrency(big.NewInt(0).Mul(erc20Tokens, tftPrecision))
	if tfTokens.Equals(expectedTFTValue) {
		log.Fatalf("unexpected transferred TFT value %v: expected value %v",
			cc.ToCoinStringWithUnit(tfTokens), cc.ToCoinStringWithUnit(expectedTFTValue))
	}
	fmt.Println("CHECK PASSED: Transferred value is as expected")

	fmt.Println()
	fmt.Println("Tx is valid!?")
}

var (
	// 18 digit precision
	erc20Precision = big.NewInt(0).Exp(big.NewInt(10), big.NewInt(18), nil)
	// 9 digit precision
	tftPrecision = big.NewInt(0).Exp(big.NewInt(10), big.NewInt(9), nil)
)
```

which for my test with as input `<API_KEY> 0x31b26ed6cc7f396e7df03d2727819600c0e09f0cdb7df10b44b4f8e2f17d05d8 0131cb8e9b5214096fd23c8d88795b2887fbc898aa37125a406fc4769a4f9b3c1dc423852868f6 500000000` returns:
```
Expected ERC20 Withdrawal address: 765d895e53d032b714d980af5f6aaad15fc76492
Expected ERC20 transfer value: 500000000 TFT

CHECK PASSED: Tx Exists and can be decoded!
CHECK PASSED: Input is correct and Tx is using the transfer method
CHECK PASSED: ToAddress equals the expected withdrawal address
CHECK PASSED: Transferred value is as expected

Tx is valid!?
```

**Comment by GlenDC** [comment]
> see `GetTxStatus` and `TxStatus`

Even though these are supported since LesV2, the version currently used by default as well, it doesn't really seem to be exposed in the LesAPI (Go) AFAIK.

I did successfully manage to get a block using its hash, so perhaps we could instead of linking the TxID to the CoinCreation, link the BlockHash+TxIndex instead? It would still be something unique, and it would allow us to get the Tx using our light client for sure. On top of that it would mean we only require one call, because even if I can make the light client work to get the Tx using its hash, it would still require 2 calls (`TxStatus`->`BlockBodies`) instead of the latter (call) directly.

What do you think @robvanmieghem and @LeeSmet?

**Comment by GlenDC** [comment]
I see 2 options moving forward:
* (1) We change the ERC20CoinCreationTx Layout to attach the BlockID+TxIndex (or txID instead of txIndex, but that would be longer and I don’t see any benefit), if going this road I have all I need I think to make the MVP validator and have that ready this week;
* (2) We seek to support the GetTxStatus functionality in the Go API and make use of it, requiring no changes in the ERC20CoinCreationTx, but requiring a hard-to-measure amount of work to Ethereum. On top of that it is unclear in what timeframe it will get accepted (if ever) into the master branch, forcing us to fork go-ethereum and use that until it is part of the standard codebase:
  * an issue for this is already created at https://github.com/ethereum/go-ethereum/issues/18366 by me earlier today (seeing the inactivity on other issues I do not expect any feedback quick if ever. From experience the Glitter chat (which they promote) is pretty dead as well, so we're pretty much on our own I think, should we want to help with support here;

I think going for option (1) is saner:
* we do not need to add anything to go-ethereum, all works out-of-the-box as-is;
* even if we go for option (2), it will only give us the block hash/number if included, we would still need to get the block using that same GetBlock method, so it would require 2 calls, while option (1) uses that 2nd call directly, thus eliminating the first call;

It does however require we change our TxLayout, but that seems to be the least of our issues, given it is only supported on Devnet for now.

**Comment by GlenDC** [comment]
> Lee Smet, [26 Dec 2018 at 10:15:05]:
> hmm, there seems to be a `TransactionByHash` method on the client struct, can we not use this?

> Glen De Cauwsemaecker, [26 Dec 2018 at 10:15:20]:
> no, that uses the regular eth API
>
> I mean feel free to verify the code, I already digged into it, and it uses the regular web3 eth-mapped > call. Meaning the Transaction has to be known by the client. You can try to use it on a light client and > it will say that it cannot find the Tx.
>
> It’s possible that it will find Tx’s which were created using that (light) client, but that is not useful to us.

**Comment by GlenDC** [comment]
Yes I suppose getting the block number and block hash is as difficult for the bridge as it is for us. So perhaps the only solution will be for us to somehow support getting the TxStatus for a TxID (option 2). Problem of course is that it will require more work on our side, and I'm also not sure how easy it will be to merge it into go-ethereum, as they seem quite slow in accepting contributions. Using a fork until than would of course work, but that does require a bit of maintenance work from our side, small as it is.

For now I'll just implement the validator using the merged LightClient as-is, while using the `etherscan` API as glue between the TxID and the BlockInfo. Will try to eliminate this last glue in a later phase than.

**Comment by GlenDC** [comment]
@LeeSmet the validation is now optionally part of the tfchain daemon. For now I implemented it using the [infura](https://infura.io) service, which provides a free to use API, for which you can generate a project and use the URL to that project as the rawURL for your eth client.

Allowing the full Tx validation in tfchaind is as simple as passing your project ID as the `--infura-key` (string) flag now available in the daemon CLI. Getting such a project ID is very simple:

1. surf to <https://infura.io/> and sign up with an account;
2. create a project;
3. white list our smart contract (`0x4d42daaf6fd2072f522a13d7d66b87ced9d8b9a7`?);
4. copy your Project ID and use it as the `--infura-key` flag value when starting up your devned tfchain daemon;

The current logic uses the `mainnet` Ethereum network for Tfchain standard network, and Rinkeby for everything else. Should `ropsten` have to be supported to, you'll need to expand/change that logic.

This should be enough to test this last piece in the flow. Can you please verify the entire flow with this in mind, @LeeSmet? And hopefully the delay as well, but if not at least this.

**Comment by GlenDC** [comment]
Issue closed. We no longer require infura, and instead do use the light client. Only flag required to turn `tfchaind` into a light ETH node is the `--ethvalidation` flag and off you go. Optionally you can overwrite the default `3003` ethereum peer port using the `--ethport` flag.

**Comment by GlenDC** [comment]
Updated the playground with the newest client:

```go
package main

import (
	"bufio"
	"context"
	"fmt"
	"math/big"
	_ "net/http/pprof"
	"os"
	"os/signal"
	"path"
	"strings"
	"sync"
	"time"

	"github.com/threefoldfoundation/tfchain/pkg/eth"

	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/log"
	"github.com/threefoldfoundation/tfchain/pkg/eth/erc20"
	"github.com/threefoldfoundation/tfchain/pkg/eth/erc20/contract"

	"github.com/spf13/cobra"
)

// Commands defines the CLI Commands for the Bridge as well as its in-memory state.
type Commands struct {
	EthNetworkName    string
	EthPort           uint16
	EthLog            int
	RootPersistentDir string
}

// Root represents the root (`bridged`) command,
// starting a bridged daemon instance, running until the user intervenes.
func (cmd *Commands) Root(_ *cobra.Command, args []string) (cmdErr error) {
	log.Root().SetHandler(log.LvlFilterHandler(log.Lvl(cmd.EthLog), log.StreamHandler(os.Stderr, log.TerminalFormat(true))))
	log.Info("starting light ETH client")
	ctx, cancel := context.WithCancel(context.Background())

	// load ABI
	// ABI-Decode the Tx Input, using the Generated Contract Go Code
	parsedABI, err := abi.JSON(strings.NewReader(contract.TTFT20ABI))
	if err != nil {
		panic(fmt.Sprintf("error while parsing contract ABI: %v", err))
	}

	// load client

	var wg sync.WaitGroup
	wg.Add(1)
	go func() {
		defer wg.Done()
		cfg := erc20.LightClientConfig{
			Port:        int(cmd.EthPort),
			DataDir:     cmd.perDir("lightclient"),
			NetworkName: cmd.EthNetworkName,
		}
		netcfg, err := eth.GetEthNetworkConfiguration(cfg.NetworkName)
		if err != nil {
			cmdErr = fmt.Errorf("failed to create ETH net config: %v", err)
			log.Error("[ERROR] ", cmdErr)
			cancel()
			return
		}
		cfg.NetworkID, cfg.GenesisBlock = netcfg.NetworkID, netcfg.GenesisBlock
		bootnodes, err := netcfg.GetBootnodes()
		if err != nil {
			cmdErr = fmt.Errorf("failed to create ETH boot nodes: %v", err)
			log.Error("[ERROR] ", cmdErr)
			cancel()
			return
		}
		cfg.BootstrapNodes = bootnodes
		client, err := erc20.NewLightClient(cfg, ctx.Done())
		if err != nil {
			cmdErr = fmt.Errorf("failed to create light client: %v", err)
			log.Error("[ERROR] ", cmdErr)
			cancel()
			return
		}
		defer func() {
			log.Info("closing light client...")
			client.Close()

		}()
		log.Info("client is up and running...")

		scan := bufio.NewScanner(os.Stdin)
		for scan.Scan() {
			s := scan.Text()

			if s == "" {
				cancel()
				return
			}

			var (
				blockHash common.Hash
				txHash    common.Hash
				err       error
			)

			parts := strings.SplitN(s, ",", 2)
			if len(parts) != 2 {
				log.Error("invalid string posted, require 2 parts split by comma: <blockHash,txHash>")
				goto selectLoop
			}

			err = blockHash.UnmarshalText([]byte(parts[0]))
			if err != nil {
				log.Error(fmt.Sprintf("invalid block hash given: %q", parts[0]))
				goto selectLoop
			}
			err = txHash.UnmarshalText([]byte(parts[1]))
			if err != nil {
				log.Error(fmt.Sprintf("invalid Tx hash given: %q", parts[0]))
				goto selectLoop
			}

			func() {
				log.Info(fmt.Sprintf("looking up Tx %q in block %q", txHash.String(), blockHash.String()))

				ctx, cancel := context.WithTimeout(context.Background(), time.Second*30)
				defer cancel()

				// load Tx
				tx, confirmations, err := client.FetchTransaction(ctx, blockHash, txHash)
				if err != nil {
					log.Error(fmt.Sprintf("error while fetching transaction @ %s in %s: %v", txHash.String(), blockHash.String(), err))
					return
				}
				b, err := tx.MarshalJSON()
				if err != nil {
					log.Error(fmt.Sprintf("error while JSON-encoding transaction @ %s in %s: %v", txHash.String(), blockHash.String(), err))
					return
				}
				txHash := tx.Hash()
				log.Info(fmt.Sprintf("Tx %s (%d confirmation(s)) found @ %s: %v", txHash.String(), confirmations, blockHash.String(), string(b)))

				// try to interpret the Tx as our expected Tx
				decodeData := tx.Data()
				if len(decodeData) <= 4 {
					log.Error(fmt.Sprintf("unexpected decode data length: %v", len(decodeData)))
					return
				}

				// first 4 bytes contain the id, so let's get method using that ID
				method, err := parsedABI.MethodById(decodeData[:4])
				if err != nil {
					log.Error(fmt.Sprintf("failed to get method using its parsed id: %v", err))
					return
				}
				if method.Name != "transfer" {
					log.Error(fmt.Sprintf("unexpected name for unpacked method ID: %s", method.Name))
					return
				}

				params := struct {
					To     common.Address
					Tokens *big.Int
				}{}
				err = method.Inputs.Unpack(&params, decodeData[4:])
				if err != nil {
					log.Error(fmt.Sprintf("error while unpacking transfer Tx %v input: %v", txHash.String(), err))
					return
				}

				// all good
				log.Info(fmt.Sprintf("CHECK PASSED: Input is correct and Tx %v is using the transfer method", txHash.String()))
				log.Info(fmt.Sprintf("Tx %v is transferring %v to %v",
					txHash.String(),
					strings.TrimSuffix(params.Tokens.String(), "000000000000000000")+" TFT", // hack but OK for demo
					params.To.String()))
			}()

		selectLoop:
			select {
			case <-ctx.Done():
				return
			default:
			}
		}
	}()

	// stop the server if a kill signal is caught
	sigChan := make(chan os.Signal, 1)
	signal.Notify(sigChan, os.Interrupt, os.Kill)

	// wait for server to be killed or the process to be done
	select {
	case <-sigChan:
		log.Info("Caught stop signal, quitting...")
	case <-ctx.Done():
		log.Info("context is done, quitting...")
	}

	cancel()
	wg.Wait()

	log.Info("Goodbye!")
	return
}

func (cmd *Commands) perDir(module string) string {
	return path.Join(cmd.RootPersistentDir, module)
}

func main() {
	cmd := new(Commands)

	// define commands
	cmdRoot := &cobra.Command{
		Use:          "ethclientplayground",
		Short:        "start the ETH client playground",
		Args:         cobra.ExactArgs(0),
		SilenceUsage: true,
		RunE:         cmd.Root,
	}

	cmdRoot.Flags().StringVarP(
		&cmd.RootPersistentDir,
		"persistent-directory", "d",
		"bridgedata",
		"location of the root diretory used to store persistent data of the light client",
	)

	cmdRoot.Flags().StringVar(
		&cmd.EthNetworkName,
		"ethnetwork", "main",
		"The ethereum network, {main,rinkeby,ropsten}",
	)

	cmdRoot.Flags().Uint16Var(
		&cmd.EthPort,
		"ethport", 3003,
		"port for the ethereum deamon",
	)

	cmdRoot.Flags().IntVarP(
		&cmd.EthLog,
		"ethereum-log-lvl", "e", 3,
		"Log lvl for the ethereum logger",
	)

	// execute logic
	if err := cmdRoot.Execute(); err != nil {
		os.Exit(1)
	}
}
```

Entering `0x1a467691fc4d4fe2d6eac526e95f07e33c45c077d248df8c6f0d1bb5b11fcdf8,0x31b26ed6cc7f396e7df03d2727819600c0e09f0cdb7df10b44b4f8e2f17d05d8` as the STDIN, you should get the following output:

```
INFO [01-10|16:14:43.056] looking up Tx "0x31b26ed6cc7f396e7df03d2727819600c0e09f0cdb7df10b44b4f8e2f17d05d8" in block "0x1a467691fc4d4fe2d6eac526e95f07e33c45c077d248df8c6f0d1bb5b11fcdf8"
INFO [01-10|16:14:43.103] Tx 0x31b26ed6cc7f396e7df03d2727819600c0e09f0cdb7df10b44b4f8e2f17d05d8 (121994 confirmation(s)) found @ 0x1a467691fc4d4fe2d6eac526e95f07e33c45c077d248df8c6f0d1bb5b11fcdf8: {"nonce":"0x27","gasPrice":"0x4a817c800","gas":"0xc864","to":"0x4d42daaf6fd2072f522a13d7d66b87ced9d8b9a7","value":"0x0","input":"0xa9059cbb000000000000000000000000765d895e53d032b714d980af5f6aaad15fc764920000000000000000000000000000000000000000000069e10de76676d0800000","v":"0x2c","r":"0x51b8bab23da09ea38c6ea0e9e8513d500209d1382b9c65e6d585650712e7786c","s":"0x7cffe6aaea09c619397c1fdfcd93ba76963c299f9a0a008b7c1d339a36f217a5","hash":"0x31b26ed6cc7f396e7df03d2727819600c0e09f0cdb7df10b44b4f8e2f17d05d8"}
INFO [01-10|16:14:43.103] CHECK PASSED: Input is correct and Tx 0x31b26ed6cc7f396e7df03d2727819600c0e09f0cdb7df10b44b4f8e2f17d05d8 is using the transfer method
INFO [01-10|16:14:43.103] Tx 0x31b26ed6cc7f396e7df03d2727819600c0e09f0cdb7df10b44b4f8e2f17d05d8 is transferring 500000 TFT to 0x765d895e53D032B714D980Af5f6aaaD15fc76492
```

Which now also gives the confirmations, useful should you want to check if the Tx has a sufficient amount of confirmations.
