### ISSUE TITLE
Basic bridge daemon that listens to the consensus set

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfchain#225]
the consensus is a module in the rivine/tfchain daemon that holds the confirmed blocks and transactions
Deployable on 0-os and with an example how to do this using the zos commandline tool to also run this locally .
As an example you can use the rexplorer https://github.com/threefoldfoundation/rexplorer .
it’s a go daemon that subscribes to the consenses set( the blockchain)

- ProcessConsensusChange function is hardcoded and execute after 6 confirmed blocks then calls an ( either create the erc20 tokens or register a withdrawal address)
- Better store the current confirmed blockheight so it can continue from there later, and for the first time we can scan from the beginning.

**Comment by xmonader** [comment]
This is how I implemented the ProcessConsensusChange

```go
// ProcessConsensusChange implements modules.ConsensusSetSubscriber,
// used to apply/revert blocks.
func (bridged *Bridged) ProcessConsensusChange(css modules.ConsensusChange) {
	bridged.mut.Lock()
	defer bridged.mut.Unlock()
	// FIXME: how to get the current height? is this the correct way?
	currentHeight := bridged.cs.Height()

	blocks := css.RevertedBlocks
	blocks = append(blocks, css.AppliedBlocks...)

	for _, block := range blocks {
		fmt.Println("BLOCK : ", block)
		height, _ := bridged.cs.BlockHeightOfBlock(block)
		fmt.Println("HEIGHT: ", height)
		fmt.Println("Current height: ", currentHeight)
		// the block we're interested in shouldn't exist.
		if height-6 == currentHeight {
			// CODE HERE FOR to create the erc20 tokens or register a withdrawal address
			// And should return afterwards.
			fmt.Println("Differs by 6.")
		}
	}
}
```
But It never enters the `differs by 6` statement Not sure if this is only triggered after being completely synced or not

**Comment by robvanmieghem** [comment]
follow up issue for the block delay : https://github.com/threefoldfoundation/tfchain/issues/229
