### ISSUE TITLE
units of TFT

### ISSUE THREAD

**Issue by GlenDC** [threefoldfoundation/tfchain#25]
We need to come up with a standard chart of units for TFT (ThreeFold Tokens), so that people know what to use and have a common language for defining names.

**Comment by GlenDC** [comment]
Fill in the question marks

| denomination | abbreviation | familiar name | value in TFT |
| --- | --- | --- | --- |
| ??? | ??? | ??? | 0 . 00 000 001 TFT |
| ??? | ??? | ??? | 0 . 000 001 TFT |
| ??? | ??? | ??? | 0.001 TFT |
| ??? | ??? | ??? | 0.01 TFT |
| ??? | ??? | ??? | 0.1 TFT |
| ThreeFold Token | TFT | ThreeFold Token | 1 TFT |
| ??? | ??? | ??? | 10 TFT |
| ??? | ??? | ??? | 100 TFT |
| ??? | ??? | ??? | 1000 TFT |
| ??? | ??? | ??? | 1 000 000 TFT |

**Comment by GlenDC** [comment]
Right now a mine fee is 1 TFT, which seeing our units seem pretty high. If it would have the same exchange with USD as BTC had that would mean the mining fee would be about 7900$ at the moment, which seems ridiculously high.

**Comment by robvanmieghem** [comment]
-9 is small enough

**Comment by GlenDC** [comment]
Rivine master latest uses now 10<sup>9</sup> as the OneCoin config variable. This is the default, and thus tfchain can also make use of it once it merges in latest of master.

**Comment by GlenDC** [comment]
As said in my previous comment _tfchain_ will also have 10<sup>9</sup> as the OneCoin value. That means the following:

| value in TFT | | description |
|---|---|---|
| 0.000000001 TFT | 1 | unit blockchain/daemon "thinks" in |
| 1 TFT | 10<sup>9</sup> | unit humans/client "thinks" in |

There are no units other than the One Coin unit (the smallest unit has no name for now).
