### ISSUE TITLE
Reset tf chain testnet

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfchain#269]
bootstrap4.testnet.threefoldtoken.com:24112 has been reset

**Comment by LeeSmet** [comment]
All bootstrap nodes have been updated as well in the meantime, which means only a few testnet nodes in the field are left

**Comment by LeeSmet** [comment]
1 of the 10 testnet nodes in the field has been reset, should sync with the latest testnet in the next few hours. Once we see that one is fine and creating blocks we can do all the other ones

**Comment by LeeSmet** [comment]
Just noticed that the faucet also needs to be updated

**Comment by LeeSmet** [comment]
faucet has been updated and is now syncing the new testnet

**Comment by LeeSmet** [comment]
7 testnet nodes have been updated in total, the other ones seem to be offline, so all online nodes under our control have been updated now
