### ISSUE TITLE
fix total block stake count tfchain production

### ISSUE THREAD

**Issue by GlenDC** [threefoldfoundation/tfchain#27]
Currently the total amount of block stakes in the `tfchain` testnet is `1000000`, while according to @robvanmieghem this is only supposed to be about `1000`.

It cannot be to high, or the POBS protocol won't be very effective.

Putting it for `0.6 transactions 2.0` milestone, as reducing the block stake count will require a reset of the testnet I think, and we'll do that anyway at the end of the `0.6` milestone, so we can take this issue with it.

**Comment by robvanmieghem** [comment]
it does not matter for the testnet but it does for the production settings

**Comment by GlenDC** [comment]
> it does not matter for the testnet but it does for the production settings

Agreed.

@LeeSmet, we need https://github.com/rivine/rivine/issues/179 to be fixed ASAP in order to solve this. As the Blockstake is one of many configs that we want to have custom for Sia.

**Comment by LeeSmet** [comment]
On the new testnet the blockstake count has been reduced to 3000. (1000 per block creator bootstrap node). We can launch the real network with a similar amount
