### ISSUE TITLE
verify why bridge builds sometimes stop syncing

### ISSUE THREAD

**Issue by LeeSmet** [threefoldfoundation/tfchain#272]
It feels like a deadlock, happened twice on the fruit. Multiple nodes were running at the time

**Comment by LeeSmet** [comment]
`2019/01/14 00:35:09.534622 diffs.go:166: WARN: block 6dc2b5853b39e1ebc3318a88c205e84e5e5f6e2ebe1a5bd49bb1571f789c1e33 cannot be applied: tx 38ac2d56a03f73c6d528dc083c4770a4b2f039f19aee65f786ed56fef4ed22c2 is invalid: invalid ERC20 CoinCreation Tx: invalid attached ERC20 Tx: failed to fetch ERC20 Tx: no suitable peers available
`

**Comment by GlenDC** [comment]
The question is also if the current approach is desirable. It is possible the Tx is valid, but due to such error we cannot verify it. Even so, the LightClient should be able to reconnect to peers if none are connected, prior to denying a Tx.

**Comment by LeeSmet** [comment]
So how are we going to approach this? I guess trying to periodically do the validation again  is the sensible solution as we can't continue to sync otherwise.

**Comment by LeeSmet** [comment]
root issue seems to be #281

**Comment by LeeSmet** [comment]
Implemented a simple continuous retry mechanism for now.
