### ISSUE TITLE
use go-bindata for explorer

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/tfchain#280]
For easier automation use [go-bindata](https://github.com/jteeuwen/go-bindata) to distribute assets.

**Comment by LeeSmet** [comment]
Which assets are you referring to? the faucet uses go templates which are already compiled in

**Comment by xmonader** [comment]
@LeeSmet I updated the title sorry for confusion

(those assets https://github.com/threefoldfoundation/tfchain/tree/master/frontend/explorer ) not sure if it makes sense as it's not a go application, but definitely better to bundle them as a binary and serve them as they won't be changing very often
