### ISSUE TITLE
tfchainc erc20 commands output json while human is the default

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfchain#288]
```
./tfchainc  wallet send erc20funds 0x76844c1cedf593be0c175e67845582e36d3bc889 1000
{
  "transactionid": "f8e6d3bb16590b474821741ea580bfa949fd8b8c0ab39ae033bb05ece310c63d"
}
```
```
./tfchainc  wallet send erc20address
{
  "transactionid": "d41c0cab80145825d84c2e5930d38f69a62978bf1834e73db165c18a8ebf688d"
}
```

**Comment by GlenDC** [comment]
It outputs human-readable JSON in the human mode. Json-mode is without all the extra spacing.

**Comment by LeeSmet** [comment]
Given the small amount of data returned by these commands, are we going to change the human readable format? We could just print it (i.e. without the curly braces and quotation marks) like it is done in the old commands, but that doesn't really make it all that more "human" readable afaic
