### ISSUE TITLE
Create an flist for an ethereum full node

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfchain#292]
geth arguments for testnet: ["--testnet", "--v5disc", "--lightserv", "90", "--syncmode", "full", "--nat", "none", "--verbosity", "4"]****

**Comment by robvanmieghem** [comment]
Asked andrew to create a build/publish example from https://hub.docker.com/r/ethereum/client-go/dockerfile

**Comment by robvanmieghem** [comment]
https://github.com/threefoldtech/jumpscaleX/blob/development_builders/Jumpscale/builder/blockchain/BuilderEthereum.py

**Comment by robvanmieghem** [comment]
Todo: package a startup script and publish it to tf_official apps

**Comment by LeeSmet** [comment]
I think to actually run this we will also need a zerorobot service, so we have a generic geth flist which can then through the zrobot service get the correct args for e.g. testnet / standard net/...

CC @zaibon

**Comment by zaibon** [comment]
That sounds about right. After it all depend what you need to do with it. If you don't have any other special logic then just starting a container, you could get away by just using a container service with the proper flist and bunch or args. So no need to have a dedicated service for it. It all depends what you need

**Comment by LeeSmet** [comment]
I don't think we want to create separate flists for testnet and standard so yeah a zrobot service seems like the way to go then

**Comment by robvanmieghem** [comment]
published flist needs to be built on linux, currently it wasa built on osx

**Comment by DylanVerstraete** [comment]
Published on: https://hub.grid.tf/tf-official-apps/geth.flist.md

Tested on a local zero-os machine and verified its running.

**Comment by robvanmieghem** [comment]
closed by https://github.com/threefoldtech/jumpscaleX/commit/17296c0b398421c631e99479c259dfbfdf4c7050
