### ISSUE TITLE
web explorer to support non local tfchaind

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/tfchain#295]
Currently web explorer works against tfchaind deployed on the localhost, no reason to make it work against remote hosts too.

**Comment by xmonader** [comment]
easier than I thought: 
The requests are only proxied to the localhost:23110 endpoints in caddyfiles in both the the local and production one
https://github.com/threefoldfoundation/tfchain/blob/master/frontend/explorer/caddy/Caddyfile.local
https://github.com/threefoldfoundation/tfchain/blob/master/frontend/explorer/caddy/Caddyfile

**Comment by robvanmieghem** [comment]
@xmonader is this still relevant then?

**Comment by xmonader** [comment]
@robvanmieghem  I solved it in the template by overriding Caddyfile
