### ISSUE TITLE
different bootstrap nodes and  genesisblock  for testnet and production

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfchain#3]
proposeto use the same binary but have a -testnet commandline flag, unless this has too much impact

**Comment by robvanmieghem** [comment]
or we modify rivine to support this

**Comment by GlenDC** [comment]
Rivine supports this now from a technical POV, once `tfchain` vendors latest of rivine we'll be able to make use of them, as to allow for such things as the proposed -testnet command line flag.
