### ISSUE TITLE
ethvalidation: Creating past withdraw event iterator failed

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfchain#302]
```
INFO [02-11|11:33:20.852] Imported new block headers               count=1    elapsed=7.726ms   number=4997696 hash=014040…65f7ea
INFO [02-11|11:33:23.442] Imported new block headers               count=1    elapsed=8.893ms   number=4997697 hash=d37bc4…67f2a7
ERROR[02-11|11:33:29.308] Creating past withdraw event iterator failed err="no suitable peers available"
INFO [02-11|11:33:42.042] Imported new block headers               count=1    elapsed=8.183ms   number=4997698 hash=ecf5d5…405fb1
```

Is this a problem or not? as the synchronization continues afterwards
in the consensus log:
```
2019/02/11 11:33:29.309081 diffs.go:166: WARN: block 8b2b80d496d4eba740ffb70cc74b6383228aa2a78a24428942aeb20afb5af09c cannot be applied: tx 70d042e74f7891e0b5b302e41ed255d6c4235e3ccb48833fd4a32d02c28724c8 is invalid: invalid ERC20 CoinCreation Tx: invalid attached ERC20 Tx: no suitable peers available
```
I only noticed this error once, is it because it is only logged once or because it is not retried?

**Comment by robvanmieghem** [comment]
arguments of the geth full node it was syncing with: ["--testnet", "--v5disc", "--lightserv", "50", "--syncmode", "full", "--nat", "none"]

**Comment by LeeSmet** [comment]
@robvanmieghem what is the exact version of the bridge?

**Comment by robvanmieghem** [comment]
It's a tfchaind build from yesterday morning

**Comment by LeeSmet** [comment]
It only gets printed once because the block validation failed due to the error, after that it marks the block id as invalid and moves on. Ethereum keeps syncing, this is normal. If tfchain itself keeps syncing that would indicate a fork

**Comment by LeeSmet** [comment]
Added retry code to the eth validation function, which should fix this problem afaik

**Comment by robvanmieghem** [comment]
Question is also why it said "no suitable peers available" while it was clearly syncing.
Also, the retry https://github.com/threefoldfoundation/tfchain/commit/10fe773812b09e722fd1cc8149ef353b85c49bad#diff-67c81917c1027c3d71fae93ba0637cb8R108 is added without removing the previous return condition https://github.com/threefoldfoundation/tfchain/commit/10fe773812b09e722fd1cc8149ef353b85c49bad#diff-67c81917c1027c3d71fae93ba0637cb8R105

**Comment by LeeSmet** [comment]
Right, moved error checking after the retry condition.

As for the sync still going, the error happened 6 seconds after the last block got fetched, and then it was 13 seconds before another block was imported, so it could indeed be there were a couple of seconds where there weren't any suitable peers, afaik

**Comment by robvanmieghem** [comment]
@LeeSmet How does this for loop respond to a kill request of the process ?

**Comment by LeeSmet** [comment]
In case the process receives a `SIGINT` the eth client will start to shut down, and methods called on it will start to return errors indicating this, so the next loop iteration will be a different error, exciting the loop and returning the error up the call chain

**Comment by robvanmieghem** [comment]
great
