### ISSUE TITLE
ability to query the status of the ethereum sync in tfchaind/tfchainc

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfchain#303]
* [x] provide a GetStatus method to the ERC20 Validator interface, which will return a struct that contains the sync information (4h)
* [x] expose this Status information as a new endpoint: `/erc20/downloader/status` (@robvanmieghem if not happy with the name, please say now, otherwise this is it); (4h)
* [x] provide a new CLI command `tfchainc erc20 syncstatus`; (4h)

**Comment by GlenDC** [comment]
Added sub tasks @robvanmieghem, so you can track progress.

**Comment by GlenDC** [comment]
Closed by merged PR #307.

**Comment by robvanmieghem** [comment]
```
tfchainc erc20 syncstatus
fetching config from daemon failed: failed to load constants from daemon's server and explorer modules: HTTP 404 error: API call not recognized: /explorer/constants
error while fetching the syncing status HTTP 404 error: API call not recognized: /erc20/downloader/status
```

**Comment by GlenDC** [comment]
ah sorry, only `bridgec` is fixed

**Comment by robvanmieghem** [comment]
when it is synced, it does work:
```
rob@homeserver:~$ docker exec tftestnet-docker_tfchaind_1 tfchainc erc20 syncstatus
Starting block height: 5151046
Current block height: 5151249
Highest block height: 5151249
```
