### ISSUE TITLE
erc20 bridgec  client

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfchain#304]
ability to query
- [x] the ethereum sync status (in progress, see #303)
- [x] the tfchain sync status
- [x] the bridge ethereum address and balance

**Comment by robvanmieghem** [comment]
@DylanVerstraete  don't forget the the tfchain sync status, did not see that in the current pull request

**Comment by DylanVerstraete** [comment]
@robvanmieghem this is added in https://github.com/threefoldfoundation/tfchain/pull/311/commits/bae5a403c30dda900a7055e6e8bfd2532c2f27b7

**Comment by GlenDC** [comment]
Closed by PR #311.
