### ISSUE TITLE
Zero Nodes monitoring issue

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/tfchain#305]
On Feb 11th a lot of the zero nodes kept going offline / online (some every 20 minutes). 
Also reports of farming servers going offline (e.g. Andreas Hartl). Is this a monitoring problem? 

Same problems today Feb 12th

**Comment by sabrinasadik** [comment]
![2019-02-12 10 50 13](https://user-images.githubusercontent.com/31733464/52626728-17cfdc00-2eb4-11e9-98c3-0828a8fa6608.jpg)


Example of messaging when screen is attached to the ZN

**Comment by zaibon** [comment]
This screenshot is irrelevant for the issue. It shows a node that is booting. So this is not related to the monitoring.

**Comment by zaibon** [comment]
Regarding the online/offline behavior, I have investigated one of the node that have that issue and it seems the problem comes from the connectivity to the node itself. For some reason it cannot reach `tff-backend.appspot.com` which is where it is supposed to send it's monitoring update.

**Comment by zaibon** [comment]
On the node I tested, it seems the connectivity to the google infrastructure is not reliably working. 
Since  `tff-backend.appspot.com` is part of the google world, there is not much we can do about it right now.

**Comment by maxux** [comment]
I'm connected to theses nodes and everything seems okay right now. I stay connected to investigate when problem comes back.

I confirm they both uses the same ISP.

**Comment by sabrinasadik** [comment]
@zaibon @andhartl can we close this issue?

**Comment by zaibon** [comment]
For me we can close it yes.
