### ISSUE TITLE
Light-wallet: encryption of reservation transaction data

### ISSUE THREAD

**Issue by zaibon** [threefoldfoundation/tfchain#315]
We need a way to encrypt a transaction data with a public key from another wallet.
So that only the owner the the wallet can read the data in the transaction

**Comment by zaibon** [comment]
@robvanmieghem can you point to the location of the code that allow encryption with the wallet key pair ?

**Comment by LeeSmet** [comment]
After discussion, we will be using JSX for the grid launch, so this will not be needed anymore
