### ISSUE TITLE
deployment of ethereum full node fails to run.

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldfoundation/tfchain#320]
Steps undertaken to deploy the ethereum full node locally on 0-os:

- Created a JSX builder that builds an flist from `ethereum-go` repository on github.
- Wrote a `startup.toml` file that defines the arguments which are needed to startup the ethereum full node.
- Uploaded this flist to `tf-official-apps` repository on the Hub [geth.flist](https://hub.grid.tf/tf-official-apps/geth.flist.md).
- Downloaded and installed JS 9 in a docker environment
- Created a Zero-OS machine in VirtualBox following the docs, [zos docs](https://github.com/threefoldtech/zos).
- Started running a 0-robot which connects to the Zero-OS machine. 
- Created a tfchain template [geth-template](https://github.com/threefoldfoundation/tfchain-templates/tree/feat/template-geth/templates/geth).
- Linked the template to 0-robot
- Spawned a container with the `geth.flist` from the tf-official-apps repository from the template.

Conclusion: when inspecting the container, no processes seem running.. Its pretty hard to complete all above steps with little or no knowlegde how these components work.. I think the process is not starting because it's not picking up the startup file or something.

startup.toml: 
```
[startup.geth]
name = "core.system"
[startup.geth.args]
name = "/bin/geth"
args = ["--{GETH_NETWORK}", "--verbosity={GETH_VERBOSITY}",
    "--lightserv={GETH_LIGHTSERV}", "--nat={GET_NAT}", "--{GETH_V5DISC}", "--syncmode={GETH_SYNCMODE}"]
```

**Comment by DylanVerstraete** [comment]
possible cause: flist is built on macOS to be run on a Linux OS. This is giving conflicts

**Comment by LeeSmet** [comment]
`go build -a -ldflags '-w -extldflags "-static"'`
-->
```bash
ldd geth
	not a dynamic executable
```

**Comment by DylanVerstraete** [comment]
Fixed in: https://github.com/threefoldtech/jumpscaleX/commit/17296c0b398421c631e99479c259dfbfdf4c7050
