### ISSUE TITLE
Move the bootstrap-peers flag to Rivine

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfchain#327]
https://github.com/threefoldtech/rivine/issues/502

**Comment by robvanmieghem** [comment]
Already moved the cli netaddressArray flag to Rivine: https://github.com/threefoldfoundation/tfchain/commit/0eb0cd1f9e695e6bfb864050ae746b3d80d2076f

**Comment by DylanVerstraete** [comment]
closed in https://github.com/threefoldfoundation/tfchain/commit/055c1d553bd6e1d0636661c6e14fdf68e512d404
