### ISSUE TITLE
Why are there custom wallet http handlers?

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfchain#328]
wondering why https://github.com/threefoldfoundation/tfchain/blob/master/pkg/api/wallet.go is not in Rivine.

**Comment by GlenDC** [comment]
I think we could move them to Rivine, they were added to tfchain as they were added not for a generic purpose in mind but in need of some tfchain-specific CLI commands (see their usage). Should you want to move them to Rivine it might be perhaps best to first reflect upon them and to see if they are in the state as they are good enough for generic purposes.

**Comment by robvanmieghem** [comment]
Will add a comment  for their use case so it's clear why they are tfchain specific

**Comment by robvanmieghem** [comment]
https://github.com/threefoldfoundation/tfchain/commit/f04aff7c5fde76487d4d9dafec141bafc0eceaa5
