### ISSUE TITLE
move the 3bot transactions to a seperate file

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfchain#331]
all erc20  related functiuonality resides in pkg/types/transactions_erc20.go.
pkg/types/transactions.go is still a huge file, it would be better to move all 3bot related code to a seperate file as well.

**Comment by DylanVerstraete** [comment]
closed in https://github.com/threefoldfoundation/tfchain/commit/28d98bf85cc5788df5520c8fdc75ae2598145cf2
