### ISSUE TITLE
Bridge does not create withdraw transactions

### ISSUE THREAD

**Issue by LeeSmet** [threefoldfoundation/tfchain#336]
From the logs it turns out that we do receive the withdraw event, and there is no failure when checking if we indeed now the withdraw address. However the tft transaction which creates the tfts corresponding to the event is not created

**Comment by robvanmieghem** [comment]
the exact logs:
```
ESC[32mINFO ESC[0m[04-24|15:38:38.161] Noticed transfer event                ESC[32mfromESC[0m=0xe5D744737bf9575A97DF3271050912BF259c0927 ESC[32mtoESC[0m=0x9019f8cEfa92dB75BE6AeffBd246385d1B82943E ESC[32mamountESC[0m=575000000000
ESC[32mINFO ESC[0m[04-24|15:38:38.162] Noticed withdraw event                   ESC[32mreceiverESC[0m=0x9019f8cEfa92dB75BE6AeffBd246385d1B82943E ESC[32mamountESC[0m=575000000000
```

**Comment by LeeSmet** [comment]
On the bridge that is being run on the fruit-jr, new withdraws are being picked up and pushed to the txpool. However, the tx seems to not get propagated to the other nodes, and so it does not end up in the chain

**Comment by LeeSmet** [comment]
Verified that the bridge is connected with at least all the bootstrap nodes, (this includes the explorers), but no transactions are being pushed

**Comment by LeeSmet** [comment]
Seems that some transactions now DID get pushed successfully and included in a block

**Comment by LeeSmet** [comment]
It seems that the initial problem where the bridge does not create withdraw transactions did not occur on the new bridge. The problem where these transactions did not propagate was resolved after fiddeling with the firewall, as this prevented connections to the bootstrap nodes. Will close this issue for now, though we now have more logging and can come back to this in case it turns out to be a problem again later
