### ISSUE TITLE
Define farmer capacity registration mechanism

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfchain#34]
New transaction type?

**Comment by GlenDC** [comment]
Could be as simple as just registering the capacity information that a farmer promises to deliver (they already started working on a script/tool to get this info from the hardware which gives as output: https://gist.github.com/chrisvdg/1c648cf5dc3edf4b52a690e17cc74e4f#file-tf_node-json).

Question is if our validation code will need to do a proof of capacity as part of the validation, or should they just always accept it. If they do need to do proof of capacity as part of the validation, we'll need to sit together with the zero-os team to check how we'll be able to do so, from any tfchain node.

**Comment by GlenDC** [comment]
Given this will now all be done in BCDB and JSX, I do not think this is still relevant. Please re-open if this changes.
