### ISSUE TITLE
light client does not always correctly mark an output as spent

### ISSUE THREAD

**Issue by LeeSmet** [threefoldfoundation/tfchain#341]
This causes the balance to be shown as larger than it should be, and could cause invalid txes to be created

**Comment by GlenDC** [comment]
JSX suffers from this as well. For JSX it has been concluded that most likely <https://github.com/threefoldtech/rivine/issues/526> is the cause of it. Once the Rivine issue has been resolved it has to be reverified if it fixes this issue or not.

**Comment by GlenDC** [comment]
Please verify if still an issue @LeeSmet, using latest code on master.
