### ISSUE TITLE
Initial size limit of transactions?

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfchain#35]
or the arbitrary data

**Comment by GlenDC** [comment]
What size limit do we deem appropriate? And if a proposed number does come up, please do explain how you came to that number.

cc @robvanmieghem, @LeeSmet

**Comment by robvanmieghem** [comment]
I would limit the size of the arbitrary data  to 83 bytes in respect to op_return in bitcoin: https://bitcoin.org/en/developer-guide#null-data
