### ISSUE TITLE
tfchaind stops syncing at block height 277851

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfchain#357]
from the consensuslog:
`2019/08/02 11:21:45.382466 diffs.go:166: WARN: block 01c243ea7d996f898d2e01d4f1417fe2751c340be33f3a7112d720e7ac633c58 cannot be applied: tx 4fb1c2ffc57abb7e6b29f778b5deb8b59418005d6ee526c4d15b394e3c66b1fb is invalid: transaction does not specify any miner fees`
 from the client:
```
$ ./tfchainc
Synced: No
Height: 277851
Progress (estimated): 82.17%
```
I deleted the complete `standard` folder and restarted, same problem
commit: b297811d30f233b36d578c553aa18f5b08884eb2

**Comment by LeeSmet** [comment]
Standard network is run entirely on the latest release (`v1.1.1` tag), at some point rivine was updated to fix this issue but special handling needs to be added for old blocks

**Comment by robvanmieghem** [comment]
reverted to commit f8c3c9d5882ec4cd3cb4f84f4e5ab69e8660ded5
```
$ ./tfchaind 
Loading...
Binding API Address and serving the API...
Loading (auto) transaction db (0/5)...
Loading gateway (1/5)...
Loading consensus set (2/5)...
Outdated consensus database... backing up and replacing
Closing consensus set...
Context is done, quitting...
context is done, quitting...
Closing gateway...
Closing transaction db...
daemon failed failed to subscribe earlier created transactionDB to the consensus created just now: failed to subscribe to consensus set: consensus subscription has invalid id - files are inconsistent
```
