### ISSUE TITLE
List invalid wallets straight in code

### ISSUE THREAD

**Issue by andhartl** [threefoldfoundation/tfchain#364]
We have users who lose their wallets. Could we make sure to include all those wallets in a blacklist such that they cannot access their TFT even when they found their seed again?

**Comment by GlenDC** [comment]
We could, however how would these users receive their coins on the new wallet.

On top of that I do not agree that the chain owners should have this kind of power.

Closing this, but feel free to take it up with @robvanmieghem in case you disagree.

**Comment by robvanmieghem** [comment]
I indeed do not agree that we should hardcode the deletion.
What we could do however is to monitor the chain to see if the tft on these addresses is being spent again, in which case you contact those people and have a legal action if necessary.
