### ISSUE TITLE
Allow passphrase passing to tfchainc from cmd

### ISSUE THREAD

**Issue by khaledkbadr** [threefoldfoundation/tfchain#37]
As I'm automating `tfchain` deployment dealing with the interactive mode is holding us from fully automated deployment. so I would suggest a flag to pass a passphrase when initing a wallet. 

If passing a flag is considered insecure, I'm open for other suggestions

**Comment by robvanmieghem** [comment]
https://github.com/rivine/rivine/blob/master/doc/examples/localnetwork/deploy_testnet.sh#L31
