### ISSUE TITLE
Mazraa wallet not working 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/tfchain#374]
Mazraa is not able to send any tokens, big or small amount. Mobile wallet gives an error that server is not reachable, but other wallets on Adnans phone (Adara, personal) do not give this error.

Desktop wallet also not working, will create separate issue under https://github.com/threefoldtech/threefold-wallet-electron
![2019-10-10 11 43 13](https://user-images.githubusercontent.com/31733464/66558414-cadffa80-eb53-11e9-98c3-544cb691baec.jpg)

**Comment by GlenDC** [comment]
Probably the developers of that App hide the real error, contact the App team and ask them to paste the real error here.

**Comment by GlenDC** [comment]
Closed, not relevant to this repo. Please open an issue with the App team, as I'm convinced that they are hiding the real error, which will also be a server error stating that the transaction is too big in size due to too many coin inputs used.
