### ISSUE TITLE
deploy v1.2.0 on std network

### ISSUE THREAD

**Issue by GlenDC** [threefoldfoundation/tfchain#375]
- [x] update all bootstrap std network nodes to the official v1.2.0 release
- [x] update all explorer std network nodes to the official v1.2.0 release
- [x] update all block creator std network  nodes to the official v1.2.0 release
- [x] update all other std network nodes controlled by us to the official v1.2.0 release

**Comment by robvanmieghem** [comment]
- [ ]We should list all nodes and if a blockstake is on it.
- [ ] if so, back up the seed
- [ ] See what is wrong with the hub.

**Comment by robvanmieghem** [comment]
to do for the future: delegated staking

**Comment by GlenDC** [comment]
@robvanmieghem no reason to still put this on this release. We're already on v1.2.1 in the meanwhile, so you're hijacking an issue here. So the delegated staking I would suggest, just put it on a v1.3 release or so. Here as a comment it is kinda lost.

**Comment by robvanmieghem** [comment]
@glendc I agree on the v1.3 but got lost on the other ones since there is no issue in a project, I could only assume this is the one that was being worked on since it is also "In progress"

**Comment by GlenDC** [comment]
This one is about the deployment, which is why your first comment is appropriate as it is about those remaining nodes still unchecked (the ones we had the meeting about this morning).

Not sure if we already have a v1.3 project, but if not, simple enough to make I guess.

**Comment by LeeSmet** [comment]
Upgraded all reachable nodes last night. 1 refused to start the new tfchain binary. The other nodes are all running. This has also bumped the amount of active bock creators on the network from 12-20 to about 35 right now. However the node overview shows only 57 nodes are online and 122 are down, ideally we would also be able to recover about 50 down nodes as well

**Comment by LeeSmet** [comment]
@sabrinasadik contacted people who's nodes are down, will see the coming days how much of them come back

**Comment by LeeSmet** [comment]
js9 setup has been installed on _kopi_, started all reachable block creators again (around 50), will back up the seeds this afternoon

**Comment by LeeSmet** [comment]
seeds recovered of 42 block creators with a blockstake
