### ISSUE TITLE
bootstrap+ explorer node with public ip's

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfchain#38]
no wallets
IP's in DNS

**Comment by LeeSmet** [comment]
185.69.166.15/24
185.69.166.16/24
185.69.166.17/24 <-- explorer
185.69.166.18/24 <-- explorer

**Comment by robvanmieghem** [comment]
185.69.166.15:bootstrap1.explorer.threefoldtoken.com
185.69.166.16:bootstrap2.explorer.threefoldtoken.com
185.69.166.17:bootstrap3.explorer.threefoldtoken.com, explorer.threefoldtoken.com
185.69.166.18:bootstrap4.explorer.threefoldtoken.com, explorer2.threefoldtoken.com
