### ISSUE TITLE
Support blocking accounts

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfchain#383]
In order to support https://github.com/threefoldfoundation/tfchain/blob/master/specs/lost_seeds.md and  a possible transition to another blockchain platform

Use the rivine authorization extension for this.

**Comment by robvanmieghem** [comment]
Requires a newly released rivine  version (v1.3)

**Comment by DylanVerstraete** [comment]
Blocked right now, we cannot disable minerfees for specific transactions at this point. Either we implement this in Rivine or we aggree to pay minerfees on authorizing / deauthorizing addresses for now.

**Comment by DylanVerstraete** [comment]
Moving it to testnet soon to confirm that it works.
