### ISSUE TITLE
threefoldradar tfchaind[22085]: Critical error: entry does not exist

### ISSUE THREAD

**Issue by nbabenko** [threefoldfoundation/tfchain#384]
Dec 18 19:58:31 threefoldradar tfchaind[22085]: Critical error: entry does not exist
Dec 18 19:58:31 threefoldradar tfchaind[22085]: Please submit a bug report here: https://github.com/rivine/rivine/issues
![2019-12-19 12 17 33](https://user-images.githubusercontent.com/4426772/71157044-ac386700-225a-11ea-9fd7-2fd6f22d141b.jpg)

**Comment by GlenDC** [comment]
@nbabenko please attach the output of `tfchaind version` for the daemon used in this log, also is this bug blocking them, as in: when they restart the daemon does block on this error again?

**Comment by nbabenko** [comment]
not actual anymore
