### ISSUE TITLE
tokens lost in transfer?

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldfoundation/tfchain#391]
I have transferred token on the TFchain (portal.test.grid.tf client) from this twin: 5GjXtYQ7ZrVXTi9AfrJx7ahcjqB3s5yiFwUpWLFU19WuZfPE
<img width="993" alt="image" src="https://user-images.githubusercontent.com/13766992/196689277-0425ab40-229a-4072-b346-bd09032f725e.png">

to a wallet on a phone 
![telegram-cloud-photo-size-4-5945154655690537522-y](https://user-images.githubusercontent.com/13766992/196689534-bc49319d-6fc7-4f1c-b8d3-18c07dac19d2.jpg)
which is wallet address: 5G9m3xYcKKJmCrvtchV3Nkiiy4zEAmeHRHccc6CwmqAF2rmR

The 400 TFT's never arrived in the wallet, but were subtracted from the portal based account (other wallet / secret). Not sure what I have done wrong and not sure what happened.

**Comment by LeeSmet** [comment]
Working as intended. The portal you used is running on testnet as per the url (note the `.test`), meaning balances seen are balances from Tfchain Testnet, and transfers initiated there are done on Tfchain testnet as well. Checking the graphql instance (again for testnet) at https://graphql.test.grid.tf/graphql with the following query

```graphql
query MyQuery {
  transfers(where: {to_eq: "5G9m3xYcKKJmCrvtchV3Nkiiy4zEAmeHRHccc6CwmqAF2rmR"}) {
    amount
    from
    timestamp
    to
  }
}
```

Indeed shows a transfer of 400TFT from the given twin address to the target address. So this is all working as intended.

As for these tokens not showing in the app: the app works against mainnet, which of course does not have this transaction.

Also worth noting, this is the old tfchain (v1) repo, which is no longer used.
