### ISSUE TITLE
testnet deployed on zero-os

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfchain#4]

**Comment by LeeSmet** [comment]
testnet deployed and blockstakes are distributed equally over the three blockcreator nodes, though 2 of those will need some time before they can participate in the consensus protocol. 

The explorer node is running but it doesnt have the caddy front end set up yet

**Comment by LeeSmet** [comment]
explorer UI is now running, the setup was manual (by cloning the rivine/explorer repo in the ubuntu container, manually installing caddy, ...) since there is currently no threefold explorer (and thus no threefold explorer docker/flist) with a pre-packaged setup
