### ISSUE TITLE
Add binary block / transactions to bottom of page in explorer web ui

### ISSUE THREAD

**Issue by GlenDC** [threefoldfoundation/tfchain#56]

**Comment by GlenDC** [comment]
These properties are now available as "hexblock" and "hextransaction", would be cool if you could give it a row, @LeeSmet.

**Comment by LeeSmet** [comment]
I guess that's easily doable. Probably best do it in  a `<code></code>` block as well

**Comment by GlenDC** [comment]
It is, but not priority and 1.0.5 is very soon, therefore I marked it as an 1.0.6 issue. The code tags sounds OK for me, I have no special reservations there, as long as I can see and copy the binary encoding of a transaction and block, I am fine with anything else.

**Comment by robvanmieghem** [comment]
Imho, this is confusing and only useful for core devs:
![image 2018-05-04 16 23 23](https://user-images.githubusercontent.com/3511318/39633163-78d7ad7a-4fb7-11e8-8db6-8af618b15d8e.jpg)
Hiding it behind a button  might be better  or being able to request it through the commandline.

**Comment by GlenDC** [comment]
Just go for the hiding behind a button, that is still easy, and it is still hidden by default. Good enough for now.
