### ISSUE TITLE
basic status visualization of the blockcreator nodes

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfchain#63]
output of` tfchainc`:
- synced
- height

output of `tfchainc wallet`:
- Unlocked
- Confirmed Balance:
- BlockStakes

**Comment by FastGeert** [comment]
@robvanmieghem are you sufficient with the current tools

**Comment by robvanmieghem** [comment]
@FastGeert  please add
- Confirmed Balance:
- BlockStakes

**Comment by GlenDC** [comment]
Number of nodes at top of all/online/offline nodes page would also be nice, as now it seems you have to manually count.

Would it be possible to also see the logs populated by the tfchain daemon of each node, or would that be not possible for some/various reasons?

**Comment by GlenDC** [comment]
There hasn't been development in this backend in ages, do not think this will be picked up ever. Closing it as no longer relevant.
