### ISSUE TITLE
threefold styled explorer

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldfoundation/tfchain#7]
- [ ] clone the rivine explorer
- [ ] minor styling improvements
- [ ] update description and any other metadata
- [ ] deploy to testnet

**Comment by GlenDC** [comment]
For the first step of this issue it would be great if we can simply copy the current rivine/explorer content into a `/frontend/explorer` directory, as discussed earlier.

**Comment by GlenDC** [comment]
@LeeSmee, no forking, but copy-paste, see:

> For the first step of this issue it would be great if we can simply copy the current rivine/explorer content into a /frontend/explorer directory, as discussed earlier.

**Comment by LeeSmet** [comment]
Initial setup has been done, not included in the build targets yet though. The icons can also use some work, though a designer should probably assist here

**Comment by GlenDC** [comment]
I think for now this is good enough. We can make issues for final design later.
