### ISSUE TITLE
Transaction might not get included in a block

### ISSUE THREAD

**Issue by LeeSmet** [threefoldfoundation/tfchain#70]
Its currently in the transactionpool of the explorer for over 100 blocks.
https://github.com/rivine/rivine/issues/286

**Comment by LeeSmet** [comment]
The transaction was included in the first block which was created by a field node (i.e. a daemon which was online before the transaction got created)

**Comment by LeeSmet** [comment]
Small example created with google charts, it's only some javascript, so performance could probably be updated by exposing the stats from the explorer module directly with a single api call instead of doing one for every block we want datapoints for.

These are examples from the last 2500 blocks:

![screenshot_20180423_171512](https://user-images.githubusercontent.com/22023708/39135772-03a00156-471a-11e8-8e1c-c5c5f4295ffd.png)
(Active bs key is timestamp here though this can be block height imo)
![screenshot_20180423_171532](https://user-images.githubusercontent.com/22023708/39135778-08244f66-471a-11e8-95a6-8ddb2d215cd0.png)

**Comment by GlenDC** [comment]
@LeeSmet this can be included, no?

**Comment by LeeSmet** [comment]
Yes, underlying issue was resolved in rivine in a39c7d5031a6237aa63a18e89f8dd18ba9c9177f
