### ISSUE TITLE
Check block creator times (ntp)

### ISSUE THREAD

**Issue by LeeSmet** [threefoldfoundation/tfchain#76]
Some blocks are created before their parent according to their timestamp. Need to check who created these blocks (the block in question and their parent), and verify the time on the respective node

**Comment by robvanmieghem** [comment]
and also the node that created the parent block, it might be lagging.

**Comment by LeeSmet** [comment]
![screenshot_20180508_223449](https://user-images.githubusercontent.com/22023708/39781650-1674da52-5310-11e8-8cef-81954c7cd318.png)


This image is pulled from the testnet graphs. at the time there were only 2 blockcreators active, both running in the lochristi dc. So it seems they are not perfectly in sync

**Comment by LeeSmet** [comment]
After thinking about this its not really an issue since the block creators calculate up to 10 seconds in the future. So if at any time `t`, a blockcreator checks and finds a block 8 seconds in the future, then the block timestamp will be `t+8`. If this block is then broadcast, and a block creator immediately finds a block, said block could have a timestamp of e.g. `t+3`, causing it to be created "before" the previous block. In this regard, block creation times of up to minus ten seconds can be explained. So this is not an issue. 

That being said, the current block acceptance time is one hour (`futurethreshold`), which means that anyone could modify the source to calculate blocks for the next 3600 seconds (1h), thus getting an advantage. In this regard we should consider changing this threshold, as well as the related `extremefuturethreshold`.

As I am writing this, it comes to mind that it is now also possible to calculate blocks "in the past", so we will need to do some verification if we can prevent this without creating issues with synchronization.

Discussion regarding these thresholds: https://github.com/rivine/rivine/issues/7
