### ISSUE TITLE
ensure that a block hash and height present the same info in the explorer

### ISSUE THREAD

**Issue by GlenDC** [threefoldfoundation/tfchain#85]
Currently the page given as the result of a block hash provides less information than that of a block height. This is a direct result of the output given by the raw REST API calls. However given that the explorer web UI is a higher level (wrapping around the REST API) it can be assumed that this higher layer provides some extra logic such that it knows when it is block hash (and it does know it because of a property given as part of the output), that it should do a secondary rest API call, so that it gets as much info as the page of a block (matched to a height) gives.

Here is an example that shows the fact that currently the page of a block, as found by height, provides more than the page of a block, as found by hash:

Found by hash:

>  <img width="798" alt="captura de pantalla 2018-05-04 a las 14 00 29" src="https://user-images.githubusercontent.com/3900482/39626843-ee51db84-4fa3-11e8-8ddc-0ae0564a7c1a.png">
> > https://explorer.threefoldtoken.com/hash.html?hash=349610dc825e5342e3b33dc89f25a71fb9279d8b09a47ff02060743ebbc91aaa

Found by height:

> <img width="816" alt="captura de pantalla 2018-05-04 a las 14 00 39" src="https://user-images.githubusercontent.com/3900482/39626881-0e8d2f84-4fa4-11e8-9348-402397c5d493.png">
> > https://explorer.threefoldtoken.com/block.html?height=10221

**Comment by LeeSmet** [comment]
As we are currently are not using a UI framework such as angular, the next best thing would be refactoring this code to leverage custom elements in http. Unfortunately, [it seems that browser support for this feature is currently not ideal](https://caniuse.com/#search=custom%20elements), even in the latest browsers. So either we refactor the separate block and graph javascript files, or we duplicate most of the logic for building the block
