### ISSUE TITLE
provide linux bootstrap node with blockstakes

### ISSUE THREAD

**Issue by GlenDC** [threefoldfoundation/tfchain#93]
It would be great to add another bootstrap node for both standard and testnet, which also has block stakes, but which runs linux instead of zero-os.

This as to ensure we have a backup node should we have a global error in zero-os, which should normally not happen, but better be safe than sorry, imho.

**Comment by robvanmieghem** [comment]
Fixed IP willl be delivered today, HW ordered

**Comment by robvanmieghem** [comment]
Should also be a bootstrap and anexplorer node , best to have two seperate containers for this

**Comment by GlenDC** [comment]
What is the status on this?

**Comment by robvanmieghem** [comment]
installing the os

**Comment by robvanmieghem** [comment]
moved  bootstrap4 to bootstrap5 and set bootstrap4.threefoldtoken.com to 109.135.19.64
